### ISSUE TITLE
quit menu item keyEquivalent

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#103]
How is it possible to activate the keyboard shortcut? I can't do it, neither when the DockDoor settings are open nor when it's closed.
If this is indeed not possible, the indication of the shortcut keys must be displayed, to avoid confusion.

**Comment by ejbills** [comment]
It works for me when I don't have CMD set for the window switcher. I'm not sure how we can disable that built-in quit shortcut. I think we should just remove it, if possible.

**Comment by ShlomoCode** [comment]
It's a macOS shortcut that should be valid in every application, I don't think it's worth removing. We just need to find a way not to display it in the menu bar but only when not in the settings window.
It is defined [here](https://github.com/ejbills/DockDoor/blob/main/DockDoor/AppDelegate.swift#L81)

**Comment by ShlomoCode** [comment]
[Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/keyboards#Standard-keyboard-shortcuts):
>**In general, don’t repurpose standard keyboard shortcuts for custom actions.** People can get confused when the shortcuts they know work differently in your app or game. Only consider redefining a standard shortcut if its action doesn’t make sense in your experience. For example, if your app doesn’t support text editing, it doesn’t need a text-styling command like Italic, so you might repurpose Command–I for an action that has more relevance, like Get Info.
>
>People expect each of the following standard keyboard shortcuts to perform the action listed in the table below.

>...

>Command-Q Quit the app.

**Comment by ShlomoCode** [comment]
Ok, I see that when focused on the window, the keyboard shortcut doesn't work. So you just need to remove the keyEquivalent from the menu bar item, and instead add a keyEquivalent for the settings window.

**Comment by ShlomoCode** [comment]
Maybe we would also like to add a "quit" button in the corner of the settings window?

**Comment by ShlomoCode** [comment]
https://github.com/sindresorhus/Settings/issues/40
