### ISSUE TITLE
Add an "Appearance" tab in app settings

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#104]
I think that in order to avoid a "wall of settings" and for a better order, it is useful to separate all the settings related to the appearance of the previews into a separate tab, and leave in "Main" only the settings related to the app itself (currently only "Launch DockDoor at login" and "Show Menu" Bar Icon")

@ejbills What are your thoughts?

**Comment by ejbills** [comment]
I have been meaning to do this for a while, this has my support
