### ISSUE TITLE
Feature request: Hide application name in preview

### ISSUE THREAD

**Issue by Arnoud-B** [ejbills/DockDoor#108]
The application name is now shown half on the preview, half outside. I suppose this is why there is such a heavy black blur behind it. This blur makes it hard to read for me, distracts and doesn't look clean like the rest of the preview.

I'm sure you have a good reason for this choice, but as the application name is superfluous anyway (as it's where the mouse cursor is positioned), why not remove it or have the option to remove it?

FYI, Hyperdock & Almighty don't show the app name either, only window names.

**Comment by ShlomoCode** [comment]
Thanks to @chrisharper22 at https://github.com/ejbills/DockDoor/pull/101, the next version will allow you to choose a "none" Hover Window Title Style, which just hides it
