### ISSUE TITLE
Bug: Oversized preview with small windows

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#110]
With small windows the preview is way oversized (in the video, Terminal is oversized compared to Xcode).

https://github.com/ejbills/DockDoor/assets/174935274/1d2555dd-14ed-458b-bc96-c63dc77f8946

**Comment by ejbills** [comment]
Duplicate https://github.com/ejbills/DockDoor/issues/36

**Comment by ShlomoCode** [comment]
> Duplicate #36

I don't think so, Terminal is a valid window, the problem is the proportions

**Comment by illavoluntas** [comment]
> Duplicate #36

I think the width has to be limited in addition to the height (currently limited). This way, you have smaller previews.

**Comment by illavoluntas** [comment]
@ShlomoCode @ejbills 
I think the width has to be limited in addition to the height. This way, you have smaller previews with transparent space on top and bottom of the preview. Well, I don't know if I made myself clear, please ask if it wasn't.
