### ISSUE TITLE
Enhancement: Put the traffic light buttons in "bottom" of the preview window

### ISSUE THREAD

**Issue by daikichi-hanayama** [ejbills/DockDoor#111]
Please put the traffic light buttons in "bottom" of the preview window.
if the preview window size is big, need to move mouse cursor long distance.

**Comment by ShlomoCode** [comment]
Working on it

**Comment by ShlomoCode** [comment]
Which user experience is better?
1. If there is an overlap display an alert. Disadvantage: less smooth experience, advantage: more clear to the user
2. Show only the options that do not overlap. Disadvantage: may confuse the user who will not understand what is happening, advantage: smooth user experience

https://github.com/user-attachments/assets/8a767e85-0798-4b0c-b419-089b9d08df40


https://github.com/user-attachments/assets/8e0d0202-bdef-4c93-872b-b7f584955448

**Comment by ejbills** [comment]
I would say 1, if a user wants to do it, they should be able to overlap.

**Comment by ShlomoCode** [comment]
But why would a user want that?

**Comment by ejbills** [comment]
Ah I see, I assumed you bundled them into one component. In that case, go with 2. Only change I would make, is that I would slap in an withAnimation(.snappy) with a 0.125 duration on the code block that hides the options to make it a bit smoother.

**Comment by ShlomoCode** [comment]
I'm still debating if the user will understand what's going on and not be confused

**Comment by ShlomoCode** [comment]
I couldn't implement the `withAnimation`, you can merge the PR and then add the smooth animation.

**Comment by ejbills** [comment]
Maybe just display that message the first time it happens?

**Comment by ShlomoCode** [comment]
I changed the order of the options, now I'm quite happy with option 2:


https://github.com/user-attachments/assets/fc35dafa-992e-4c9f-bc5f-b73e7d796fe2

**Comment by ShlomoCode** [comment]
After further thought, I think we'll go with option 1.

**Comment by ShlomoCode** [comment]
After further thought, I think we'll go with option 1.
