### ISSUE TITLE
Integration to a Web Localization Platform for Beginners

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#114]
It is useful to reach additional audiences. It is important to make the localization suitable even for those lacking any technical knowledge, by interfacing with a web interface for translation, and pushing/pulling by Github Actions.
I found for example this:
https://localazy.com/blog/automated-localization-github-actions-localazy

A very beautiful and friendly platform. Free up to 200 source keys (currently we have 76). Alternatives can be explored.

**Comment by ShlomoCode** [comment]
Crowdin (less pretty) : https://github.com/marketplace/actions/crowdin-action (https://crowdin.com/page/open-source-project-setup-request)

**Comment by ShlomoCode** [comment]
Transifex (quite pretty): https://www.transifex.com/open-source, https://github.com/apps/transifex-integration

**Comment by ShlomoCode** [comment]
@ejbills What are your thoughts I think that technically such a thing must be defined by the repo owner because it requires setting Actions Aecrets or granting permissions to the Github App.

**Comment by ejbills** [comment]
I like transifex the best I think, is there any setup required for integrating it with the Xcode localization files? Will sit down and dig into it later today.

**Comment by ShlomoCode** [comment]
From my experience, the transifex dictionary is worth almost nothing. Crowdin's for example is much better.
