### ISSUE TITLE
FR: show multiple rows in single hover window

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#116]
![Screenshot](https://github.com/ejbills/DockDoor/assets/174935274/85891b0f-5986-4e19-93b7-0ecdbe29333c)

Bad UX (no scroll indicators). It is off screen, but you should be able to scroll to the right and see the whole window. This will be remedied in the near future, I'm not happy with how it handles lots of windows.

**Comment by ejbills** [comment]
Kind of bad UX, you can scroll to the left and right on your windows. It is off screen, but you should be able to scroll to the right and see the whole window. This will be remedied in the near future, I'm not happy with how it handles lots of windows.

**Comment by ejbills** [comment]
Consolidating: https://github.com/ejbills/DockDoor/issues/84
