### ISSUE TITLE
Bug - Tab key doesn't work

### ISSUE THREAD

**Issue by ChrisRuybal** [ejbills/DockDoor#119]
MacOS 14.5.  When the hot key is left at the default CMD-Tab, using the tab key in any other app fails.  It seems that the keypress isn't getting past DockDoor to the other apps.
If I change the hot key to CTRL-Tab, the tab key works as expected in other apps.

**Comment by illavoluntas** [comment]
See #92 
This has been noted by the developer

**Comment by ChrisRuybal** [comment]
Problem solved.  I got notification of the new release right after I created this bug.  Thanks!

**Comment by illavoluntas** [comment]
No problem!
