### ISSUE TITLE
Changelog in dark mode

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#123]
Could the changelog be dark to have continuity (in the case of the screenshot) ?

_Originally posted by @illavoluntas in https://github.com/ejbills/DockDoor/issues/120#issuecomment-2218658982_

**Comment by illavoluntas** [comment]
Here is the mentioned screenshot. 

![image](https://github.com/ejbills/DockDoor/assets/174935274/b73e11f2-8cd4-4030-809d-6227c52b65c7)
