### ISSUE TITLE
Proper string keys

### ISSUE THREAD

**Issue by ejbills** [ejbills/DockDoor#129]
Also, should proper string keys be considered?

_Originally posted by @chrisharper22 in https://github.com/ejbills/DockDoor/issues/128#issuecomment-2219285600_
            
            
Localization should have proper string keys.

**Comment by ShlomoCode** [comment]
If the string is too general, `comment' can be used to display additional information.
Do we really want that overhead of keys?

**Comment by chrisharper22** [comment]
Was this closed by accident, or are string keys not on the to do list?

**Comment by ejbills** [comment]
Well, doesn't crowdin solve this essentially? Or do you still recommend string keys?

**Comment by chrisharper22** [comment]
> Well, doesn't crowdin solve this essentially? Or do you still recommend string keys?

Oh, to be honest I've never looked into what Crowdin provides, nor looked at the recent PRs involving it. If it is sufficient for localization then forget I commented here! Totally my bad.

**Comment by ShlomoCode** [comment]
Crowdin has a smart dictionary feature that brings up similar strings as suggestions.
From my experience translating the iina app through Crowdin is really good, and I think it may solve the problem of translations that are reset due to a small change in the source string, because in such a case Crowdin knew how to offer the previous translation, and in one click save it again.

**Comment by chrisharper22** [comment]
> Crowdin has a smart dictionary feature that brings up similar strings as suggestions. From my experience translating the iina app through Crowdin is really good, and I think it may solve the problem of translations that are reset due to a small change in the source string, because in such a case Crowdin knew how to offer the previous translation, and in one click save it again.

Perfect, thanks for explaining it! Never mind me bringing up this PR.
