### ISSUE TITLE
Enhancement suggestion (dock peeking): user-defined setting to reduce or turn off motion effects 

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#13]
Consider a user-defined setting to turn off the motion effects that are currently used to display the preview window pop-up when dock peeking. Dock peeking heavily employs motions effects that can be distracting. With motion effects turned off, the expected behavior when dock peeking would be to show the fully rendered preview pop-up when a dock icon is clicked.

**Comment by ejbills** [comment]
Will be in 1.0.3

**Comment by ejbills** [comment]
I see, I thought you just wanted to disable the sliding animation. You want global, entire disabling of animations, correct?

**Comment by 0n0mat0p03ia** [comment]
> I see, I thought you just wanted to disable the sliding animation. You want global, entire disabling of animations, correct?

That's my personal preference, I generally find animation effects a bit distracting. It's nice to give the user a choice to enable/disable if possible. People with certain motor or visual issues might appreciate this too. 

Not sure if you want to implement a single global setting, or allow users to enabled/disable individual effects. I'll leave that up to you.

**Comment by ejbills** [comment]
@0n0mat0p03ia in the next version, it will be possible to turn off the gradient animation, and just make it a static overlay (as you can control the animation speed). Are there any other areas in the current version of dockdoor you think should have options for reduced motions?

**Comment by 0n0mat0p03ia** [comment]
> Are there any other areas in the current version of dockdoor you think should have options for reduced motions?

Nothing comes to mind at the moment.

**Comment by ejbills** [comment]
> Nothing comes to mind at the moment.

Closing the issue for now then, if anything comes to mind please re-open this issue and let me know :)
