### ISSUE TITLE
Option to disable the dimmed traffic light buttons

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#131]
I really don't like the change presented at https://github.com/ejbills/DockDoor/commit/e9b1c809fa06278e34d9611ecf7690812932f2e0.
Especially in a preview of a colored window, the buttons blend in with the window's content and it is difficult to distinguish their location at a glance.

**Comment by ShlomoCode** [comment]
I think we'll do this as an select:
- Preview window's traffic light buttons Visibility:
- - On window hover; Dimmed until button hover
- - On window hover; Full opacity
- - Always visible; Full opacity

**Comment by chrisharper22** [comment]
I think the best bet here is to go with option A, which sounds like it mimics macOS' default buttons

**Comment by ShlomoCode** [comment]
On macOS:
- When the window is focused the buttons are in full color, when hovering over them the icon appears inside the button
- When the window is not focused the buttons are gray, when you hover over them they are colored and the icon appears

What DockDoor is doing right now is playing with the opacity. I really don't like it.

**Comment by ejbills** [comment]
I played around with making them gray circles, like the default macos behavior - but I didn't think it looked good. Though, I like the idea of these options. I will add in these options tomorrow.

**Comment by ejbills** [comment]
@ShlomoCode mind pulling my latest commit and making sure it works as expected? in my testing, everything is working smoothly.

**Comment by ShlomoCode** [comment]
I'll check it out and update.
p.s. I recommend using "closes #XXX" in the commit description as it gives us more context as to why the change was made. Now it's clear to us, but if we want to understand in half a year why this commit was made exactly like this?...

**Comment by ShlomoCode** [comment]
It seems to be working well :+1:
One thing - you should display the last option (Never visible) as the first, so that the selection is in ascending order:
`Never visible > Partial display > Always visible; Full opacity`
This will make the options easier to understand.

**Comment by ShlomoCode** [comment]
https://github.com/ejbills/DockDoor/pull/137
