### ISSUE TITLE
Make symbols of traffic lights dark for light mode too 

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#132]
See this. 
![image](https://github.com/ejbills/DockDoor/assets/174935274/47276ea2-e137-443b-a7a6-7b6365d1c96a)

The current buttons have their x, - and <> ~~transparent~~ white, and it can be hard to read them.
Maybe they could become ~~opaque~~ adapted to the light color as macOS. 
I don’t know if this is was planned in #131.

**Comment by illavoluntas** [comment]
The text inside is in fact white (in DockDoor) and I suggest that it matches the macOS style (especially because the minus of the yellow light is extremely difficult to read).

**Comment by illavoluntas** [comment]
This seems to be changing according to the light or dark mode, because I use light mode on my Mac and it differs from the changelog screenshot which is dark mode. 

![image](https://github.com/ejbills/DockDoor/assets/174935274/e3821af2-c482-41fd-9542-cae583a1b7cd)

**Comment by illavoluntas** [comment]
![Capture d’écran 2024-07-10 à 14 53 59](https://github.com/ejbills/DockDoor/assets/174935274/3fdefd40-3d4f-4bdf-94ce-2993787cbf52)

When a window is white, the text inside the buttons is white (because it is transparent).

**Comment by illavoluntas** [comment]
Sorry about that, I was thinking it was time to close it. I forgot a PR was intended to close it. It won’t happen again

**Comment by ShlomoCode** [comment]
The logic is that until a fix has been submitted and merged in practice we don't want to close the problem, otherwise it could slip away if at the end of the PR we forget/reject
