### ISSUE TITLE
Bug: Preview window is movable

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#134]
The preview window can be moved if carefully done. With third-party apps like [Rectangle](https://github.com/rxhanson/Rectangle) the window can even be resized. When the mouse leaves the area where the preview window is, it disappears.

https://github.com/ejbills/DockDoor/assets/174935274/4d1bc4e5-ca65-4a1a-891a-584dcdffa07b

**Comment by ejbills** [comment]
Lol.. that is kind of funny. I will disable that!

**Comment by ejbills** [comment]
Fixed in [latest commit](https://github.com/ejbills/DockDoor/commit/eae0b70796bbada2f3411ae03e726fe9ae79945e)
