### ISSUE TITLE
Window previews slightly hidden behind dock

### ISSUE THREAD

**Issue by langjacob518** [ejbills/DockDoor#136]
I typically have the dock hidden, and I've realized that windows previews "tuck" behind the dock when dock hiding is turned on (but it works as expected when turned off). It's not such an issue for previews, but does make minimized and hidden windows hard to use. Hard to describe so here's a screen recording (hopefully this works):

https://github.com/ejbills/DockDoor/assets/167139396/d73f72a8-1ccb-48c4-a385-949185c0911e

Also, as a feature request, I'd love to be able to get rid of the app name bubble. I know DockView does this, so it should be possible but I'm no coder by any means. 

Again, love the app. I think it's the best of it's kind and I get excited with every update (and I'm amazed at how frequently those come!). Cheers for a great app.

**Comment by ejbills** [comment]
Please adjust your "window buffer" setting, increase it a bit until it is perfectly aligned. 

@chrisharper22 just released an option to turn off the app name bubble in the latest release. Both of these options are present in v1.1.0. Thanks for using the app! :)

**Comment by langjacob518** [comment]
Haha dude sorry I'm so inept. Thanks for the fast reply, what is the name of the app bubble setting? I'm sure it's hiding in plain sight in the settings but I'm just not seeing it.

**Comment by ejbills** [comment]
<img width="584" alt="Screenshot 2024-07-10 at 10 42 21 AM" src="https://github.com/ejbills/DockDoor/assets/74191134/7868d4b2-a861-45ea-ad58-4d934c3d7f1b">

**Comment by ejbills** [comment]
in the appearance tab

**Comment by langjacob518** [comment]
Hmm, I'm seeing something a little different. Wondering if it's a bug in the latest release or if I'm just having a massive brain fart. Running 1.1.0 and quit the app before taking this screen recording to make sure and updates were incorporated. 

https://github.com/ejbills/DockDoor/assets/167139396/7881c53a-c6dc-47db-969f-006e18569c11

Thanks for being patient with me.

**Comment by ejbills** [comment]
Sorry... my video is from the pre-release version and we renamed it, so it is titled different.  In your video you can see "Hover window title style" which you have set to embedded. Change that to "hidden" and voila, should be good to go.

**Comment by langjacob518** [comment]
Sorry, I mean the text bubble, not the window preview. When I set that to hidden and quit the app I'm still seeing the text bubble. Like in the thumbnail of my first screen recording on my original comment, the bubble that just says "Microsoft Excel" right above the app, not the one in the top left of the window preview. The "hidden" setting just seems to get rid of the one in the top left, I'm hoping to get rid of the one directly above the app and obstructing the window preview.

**Comment by ejbills** [comment]
OH like the default macos label? Ok I get you now, I will need to look into that. As that is built into macOS, I will need to do some digging on how we can disable that. 

Looks like its possible(see Ed Palmas response):
https://discussions.apple.com/thread/909301?answerId=4331407022&sortBy=best#4331407022

However it seems a bit technical, so you can do that if you feel comfortable. I will look into automating this via DockDoor soon. 
Can you open a new issue for this as a feature request?

**Comment by langjacob518** [comment]
Sure thing, thanks!
