### ISSUE TITLE
Ctrl+Tab: navigating window preview list impractical when many windows are open

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#14]
As a user, I find it tedious to locate and select a window in the Ctrl+Tab list when many windows are open. It can require tabbing many times (or a lot of scrolling) to locate the desired window, which may be at the end of the list.

A grid/card layout that shows more preview windows at once (as is done is other similar apps) might work, or some other UI/UX solution that reduces the amount of tabbing/scrolling sometimes needed to find the desired window.

**Comment by ejbills** [comment]
Consolidating with: https://github.com/ejbills/DockDoor/issues/6
