### ISSUE TITLE
Question: How to get the launched key reset

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#157]
Yes, they have a built-in reset method: https://github.com/sindresorhus/Defaults#reset-keys-to-their-default-values

              Note that we must not reset the `launched` key, otherwise the user will suddenly get a "Welcome" window... 😀

_Originally posted by @ShlomoCode in https://github.com/ejbills/DockDoor/issues/142#issuecomment-2221780758_
            
 For testing purposes (translation), I would like being able to completely reset the application, even the launched key, to see if the translations are accurate in their context.

**Comment by ShlomoCode** [comment]
@illavoluntas Run this command in `Terminal.app`:
```
defaults delete com.ethanbills.DockDoor
```

There is also [Prefs Editor](https://apps.tempel.org/PrefsEditor/) which provides a nice GUI.

**Comment by illavoluntas** [comment]
Thank you @ejbills!
