### ISSUE TITLE
Enhancement suggestion (Ctrl+Tab): display app favicon and name in preview window list

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#16]
As a user, I can't easily see at a glance which window(s) below to which app(s) in the Ctrl+Tab preview list.

Suggestion: the same as for dock peeking, consider displaying each app's icon and name in the Ctrl+Tab preview window list. Specifically, show the app icon/name only for app's first window in the list. Or, implent other UI changes that would help users identify at a glance which window(s) belong to which app(s) in the Ctrl+Tab list.

**Comment by ejbills** [comment]
app icon is not planned, but i recently added the window title to the switcher :)
