### ISSUE TITLE
chore: Update French locale

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#160]
I have updated completely (for the moment) the French locale using Crowdin. Waiting for approval. 

Notice that strings "Restart required" and "Please restart to apply the changes" (cropped) are missing.
![Capture d’écran 2024-07-11 à 08 18 04](https://github.com/ejbills/DockDoor/assets/174935274/c5171de9-a279-498f-a88b-bd21abdd3a22)

**Comment by ShlomoCode** [comment]
> Notice that strings "Restart required" and "Please restart to apply the changes" (cropped) are missing.

Fixed at https://github.com/ejbills/DockDoor/pull/168
