### ISSUE TITLE
Bug: Finder does not relaunch when quit

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#164]
If you try to quit Finder with DockDoor, the dot under the Dock icon is not present, possibly meaning the app wasn't relaunched automatically (when you enter `killall Finder` on `Terminal.app`, the Finder is automatically relaunched).
Using Option + Quit might or might not have unexpected consequences (which I have not tested).

https://github.com/ejbills/DockDoor/assets/174935274/f7f9bcba-b28b-41f1-b00f-947bd046c223

**Comment by ShlomoCode** [comment]
https://github.com/lwouis/alt-tab-macos/issues/1328
https://github.com/lwouis/alt-tab-macos/issues/362

**Comment by illavoluntas** [comment]
So what do I do about the status of this issue?

**Comment by ShlomoCode** [comment]
The subject needs to be researched, for now I just brought some relevant links

**Comment by illavoluntas** [comment]
In my opinion Finder does **not** have to be relaunched automatically.
