### ISSUE TITLE
[BUG] Hover delay makes window show up even if mouse is not over icon anymore

### ISSUE THREAD

**Issue by ejbills** [ejbills/DockDoor#17]
## Describe the bug

The easiest way to observe this:
- set the "Preview Window Open Delay" to 2 seconds
- move the cursor over an app icon
- and move it away _upwards_ quickly(!) above of the space where the previews would usually be displayed

After the delay, the preview will still appear which is already false because the mouse is not hovering over the app icon or an active preview anymore (but it also happens with no or very small delay settings). 

However, often times the preview does not even disappear anymore, sometimes you can even move your cursor sideways or downwards and nothing will happen. Only when you (significantly) move the cursor upwards the preview disappears. This behavior is especially annoying when you accidentally hover over the dock and then the preview is stuck on your screen.

## Expected behavior
The dock previews are only show while you hover directly over an app icon or an active preview

## Environment
 - macOS version: tested it on all supported macOS versions
 - App version: with the latest DockDoor version

## Additional context

- [x] I have reviewed the open issues to ensure this is not a duplicate

source @tmnrdhf

**Comment by claycle** [comment]
I suppose this is the same bug (ie, one should never see this and it has something to do with the hover delay):
<img width="2560" alt="Screenshot 2024-06-26 at 7 47 06 AM" src="https://github.com/ejbills/DockDoor/assets/419840/bf9ae07a-6585-4ed5-a248-f636798a0762">

**Comment by claycle** [comment]
A better image displaying the bug behavior:
![hover](https://github.com/user-attachments/assets/828d47e7-e08c-4e43-a0d6-8b5d1e2beb74)

**Comment by ejbills** [comment]
@claycle your issue is unrelated to this post, but it will be addressed in https://github.com/ejbills/DockDoor/pull/254 as we are revamping how the mouse location is calculated. Stay tuned!

**Comment by tmnrdhf** [comment]
@ejbills are there any plans to address this? That the [dock preview gets stuck and is displayed permanently](https://github.com/ejbills/DockDoor/issues/327) is the #1 problem that keeps me from using dockdoor.

**Comment by ejbills** [comment]
I'll do this issue next @tmnrdhf.

**Comment by ejbills** [comment]
@tmnrdhf v1.3.3 is out which fixes this issue.

**Comment by tmnrdhf** [comment]
@ejbills thanks a lot for your effort!

However, unfortunately this issue is not yet fixed. Only when you move the cursor straight up vertically it works now, but when you move it at an angle it still gets stuck very often. I feel like it could be connected to the "Natural Mouse Movement" from v1.3 or #364. (I feel like it always gets stuck when the cursor slightly touches another icon before moving upwards. But it also sometimes seem to depend on the speed of the cursor, which is odd and I can't really find a pattern for it.)

**Comment by ejbills** [comment]
Can you attach a video? I can't reproduce.

**Comment by tmnrdhf** [comment]
Sure thing: 

https://github.com/user-attachments/assets/f01203cc-8eb3-4733-9cbb-6d3a2b8288f1

**Comment by ejbills** [comment]
I see, it's like the mouseEntered event never happens in the window. I will debug this further, thanks for the clip.

**Comment by tmnrdhf** [comment]
Thanks for looking into it!
