### ISSUE TITLE
The image in preview hover action is blurry

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#179]
The preview image for `Preview hover action->See a preview of the window enabled` is a bit fuzzy/blurry. `Use Uniform Image Preview Radius` is enabled (I disabled it, didn't make a difference). 

_Originally posted by @0n0mat0p03ia in https://github.com/ejbills/DockDoor/issues/32#issuecomment-2224251498_

**Comment by ShlomoCode** [comment]
https://developer.apple.com/forums/thread/739593

**Comment by ejbills** [comment]
This will be fixed in the next release, I just pushed the fix to main.
