### ISSUE TITLE
Placing pointer over dock icon generates preview hover unexpectedly

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#180]
v1.1.2

Looks like there's an issue when `See a preview of the window enabled` is enabled.

Scenario is two adjacent apps in the dock:

abc_app w/ one window, not minimized or hidden (in screen recording, VS Code)
xyz_app w/ one window, minimized (in screen recording, Firefox)

Steps to reproduce:

1. Hover pointer over xyz_app dock icon (the minimized app)
2. Slide the pointer over to abc_app dock icon and hover

A preview hover for abc_app is shown even though the pointer remains on its dock icon. The expected behavior is for the preview hover image to be generated when the pointer is hovered over abc_app's preview window pop-up (i.e., dock peek). The preview hover image should not be generated when the pointer hovers over abc_app's dock icon.

https://github.com/user-attachments/assets/615e5643-baca-4422-87d9-e50e4e1477ba

**Comment by ejbills** [comment]
Was able to reproduce, fixed it. Will be in next release! Hopefully it's not too annoying till then.
