### ISSUE TITLE
Dock Previews Do Not Activate When Cursor Is Below Icon

### ISSUE THREAD

**Issue by the-0verlord** [ejbills/DockDoor#19]
The previews in the dock only activate when the cursor is directly on top of the icon. However, my muscle memory on the dock is based on bringing the curser all the way to the bottom of the screen so that it is below the icon. In the dock, this action highlights the app and makes it clickable. However, previews do not appear when doing this. I've added a screenshot below.
![Screenshot 2024-06-24 at 11 49 24 PM](https://github.com/ejbills/DockDoor/assets/173755792/d6df96e4-7fe4-4167-8bc7-acd12c673589)

**Comment by neilroy1998** [comment]
This would be really awesome to have. As when we have our dock below or to the right/left, we tend to just throw our mouse pointer, and we do not see the preview as it's "below" the dock...

**Comment by chrisharper22** [comment]
I had this working while working on #182, but as I was finishing up, it ended up throwing off calculations for the window's position, so I discarded it. This should still be possible to implement, at some point.
