### ISSUE TITLE
No hover action not working.

### ISSUE THREAD

**Issue by Levfreak** [ejbills/DockDoor#195]
Hello,

When the setting "No hover action" is enabled the the window previews from the dock still show up. Presumably, the setting is supposed to disable the dock preview for those who simply wish to use the window switcher.

Would be great to have this fixed!

Thanks!

**Comment by ShlomoCode** [comment]
> Presumably, the setting is supposed to disable the dock preview for those who simply wish to use the window switcher.

No, it controls what happens when you hover over the preview itself
Currently there is no option to disable the dock preview

**Comment by ejbills** [comment]
Hi there, if you are looking for only the window switcher, I recommend using the much more mature project AltTab:
https://github.com/lwouis/alt-tab-macos

**Comment by Levfreak** [comment]
Thank you!
