### ISSUE TITLE
Window Switcher Order: Recently Focused

### ISSUE THREAD

**Issue by SarcevicAntonio** [ejbills/DockDoor#196]
I thought I could replace AltTab with this more modern app, but a blocker is the window switcher order. I want to quickly and blindly switch between the last two apps back and forth (i.e. code editor + browser) with just a single keyboard shortcut. Setting AltTabs "Window order" to "Recently Focused" allows me to do this. The current app is at the start of the list, and the first app selected is the second last focused app. Pressing the shortcut quickly just opens the last app, as I also have a slight apparition delay of 150ms enabled which also means the window switcher itself isn't even shown for this quick back and forth switching, but I can live without that.

**Comment by ejbills** [comment]
@hasansultan92 and I have been slowly cooking a major update which adds minimized window previews, hidden previews, and multi desktop space support. This will be addressed once we are done. We will be sorting the windows by last active time stamp, so it will allow you to switch to the last active window relatively seamlessly. Please stay tuned!

**Comment by ShlomoCode** [comment]
I hope there won't be too many conflicts with the refactor I'm cooking 😆

**Comment by SarcevicAntonio** [comment]
Very nice to hear, looking forward! 🙌😁

**Comment by HuaDeity** [comment]
I just discovered this app today and I'm excitedly anticipating this feature.

**Comment by HuaDeity** [comment]
I am curious to know if DockDoor can detect windows being opened through wine.
