### ISSUE TITLE
Preview Hovers not clickable when Dock is set to auto hide/show

### ISSUE THREAD

**Issue by jacobcassidy** [ejbills/DockDoor#200]
If the setting: `macOS > System Settings > Desktop & Dock > Automatically hide and show the Dock` is selected, when trying to click on a Hover preview, the dock will hide and the preview will disappear, thus being unclickable.

Either the Dock should remain active while the hover preview remains active, or the hover preview should remain active long enough to move from the dock that is hiding away to the preview to select it.

**Comment by ejbills** [comment]
Thanks for opening this issue. 

This likely stems from the hover window being too far from the dock. I use and developed DockDoor with auto-hiding enabled, so I am pretty familiar with this issue. 

Please go into the settings, and in general, go go 'Window Buffer' and try to decrease it until there is no gap between the dock and the window. This should solve your issue.

**Comment by jacobcassidy** [comment]
Thanks @ejbills. That works, and I'll use that solution for now.

I was thinking that a great feature would be if the preview had a setting to delay how long it stays around before disappearing when leaving the dock, or even a fade-out effect that can still be activated by hovering over it before it fades out.

**Comment by ejbills** [comment]
> I was thinking that a great feature would be if the preview had a setting to delay how long it stays around before disappearing when leaving the dock, or even a fade-out effect that can still be activated by hovering over it before it fades out.

Could you open a new issue as a feature request for this funtionality?

**Comment by jacobcassidy** [comment]
Done!

**Comment by josephtribulat** [comment]
> Thanks for opening this issue.
> 
> This likely stems from the hover window being too far from the dock. I use and developed DockDoor with auto-hiding enabled, so I am pretty familiar with this issue.
> 
> Please go into the settings, and in general, go to 'Window Buffer' and try to decrease it until there is no gap between the dock and the window. This should solve your issue.

Hello. I'm having the same issue, but this solution doesn't work for me. Even with the offset, the preview disappears when I move the cursor over it. I've tried with the preview aligned just right to the dock, or with an overlap between both. In either case the preview disappears as soon as my cursor leaves the dock zone. My dock is vertical, on the right side of the screen, in case that makes a difference.

I've been looking in the settings for the parameter suggested by @jacobcassidy before I found this issue.
