### ISSUE TITLE
Code Lint automation

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#204]
I'm thinking of using https://github.com/nicklockwood/SwiftFormat

- [x] A build phase in Xcode (https://developer.apple.com/documentation/xcode/running-custom-scripts-during-a-build)

**Comment by hasansultan92** [comment]
Cant we just make a script to use the default file formatter from Xcode? Make a hook and as a pre-commit the bash script runs and then the commit goes through?

**Comment by ShlomoCode** [comment]
It is possible? XCode supports formatting all files via the command line?

**Comment by hasansultan92** [comment]
Not sure to be honest, I know we have to use Xcode in the command line to install stuff like git on Macs for the first time, so I figured there might be something like this. We can do some more research into this, I like the overall idea of using some sort of a linter regardless

**Comment by hasansultan92** [comment]
Did some research, I cant seem to find much about Xcode having capabilities in the command line.
