### ISSUE TITLE
No preview for Visual Studio Code, Calendar, Finder

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#21]
When I hover over the Dock icon of these applications nothing happens.
Version 1.0.5, macOS 14.5

**Comment by ejbills** [comment]
I will take a look

**Comment by ShlomoCode** [comment]
It's weird - it does work now for Finder (for VSCode and Calendar not yet). Probably for Finder this is some edge case, I will try to understand how to exactly reproduce the problem.

**Comment by ejbills** [comment]
Are you positive vscode and calendar have active windows open? Apps can be "active" without any windows being open - hence the confusion. Or its possible their windows are in another desktop space, which isnt supported yet.

**Comment by ShlomoCode** [comment]
> Are you positive vscode and calendar have active windows open?


Yes of course. I made a screen recording for a demonstration where you can see that a preview does not appear for an open VSCode window, while for other applications (for example iTerm) it does:

https://github.com/ejbills/DockDoor/assets/78599753/b7f78c50-0a24-401b-85c0-c9593ca55c51

For you it shows for VSCode?

**Comment by ejbills** [comment]
It wasn't showing vscode for me either, I fixed it. Will be in next release.

**Comment by ShlomoCode** [comment]
Great. This should also fix Apple Calendar?

**Comment by ShlomoCode** [comment]
If you'd like to push the fix commit I can confirm if it does fix the problem (I'm actually currently running a local DockDoor build I built using XCode, with Ctrl + Tab functionality disabled).

**Comment by ejbills** [comment]
Just pushed to main, give it a try and let me know!

**Comment by ShlomoCode** [comment]
Now works for open VSCode window, but not for minimized VSCode. For Calendar does not work at all, not even if it is open
https://github.com/ejbills/DockDoor/assets/78599753/02e45934-368b-4c92-9bc8-8b928c844d3f

**Comment by ejbills** [comment]
OK, I think I know the issue. I think it's the app name matching, it looks like your system applications are using a different language so the window can't find the match.

Can you please add this to line 257 of WindowUtil.swift
print("Owning application: \(app.applicationName)")
print("Searching for: \(applicationName)")

and hover over calendar, let me know what it says?

**Comment by ShlomoCode** [comment]
Looks like you're right! And when I change back the language of Calendar (in System Settings > Language & Region > Applications) to "System Default - English" the preview works.
![CleanShot 2024-06-25 at 21 31 41@2x](https://github.com/ejbills/DockDoor/assets/78599753/8865de6a-c998-4fc2-bb45-15f340359259)

**Comment by ShlomoCode** [comment]
This happens because macOS does not apply the localization to the title in the Dock and Launchpad when the language is changed only for the application and not for the entire system, but it does change the window title...

**Comment by ejbills** [comment]
Can you print out the applicationName.localizedLowercase?

**Comment by ejbills** [comment]
I switched my locale to hebrew, and calendar previews appear to be working for me...

**Comment by ShlomoCode** [comment]
Yes, when the application and the system are the same, there is no problem, because both the window title and the name in the Dock are translated and identical. The problem is caused when the system is in one language, and a specific language is selected for the application (this is a built-in option of macOS). For example, an English system, and the Hebrew language was selected for the calendar app. In this case, the name in the Dock remains in its English version but the window title is the translated version, thus creating a mismatch.

**Comment by ShlomoCode** [comment]
![CleanShot 2024-06-25 at 22 53 43@2x](https://github.com/ejbills/DockDoor/assets/78599753/068301bb-66de-4d83-aebe-195ec185313f)

**Comment by ShlomoCode** [comment]
![CleanShot 2024-06-25 at 22 55 25@2x](https://github.com/ejbills/DockDoor/assets/78599753/fb64b620-cb6e-43f6-a230-1500939fabe0)

**Comment by ShlomoCode** [comment]
> Can you print out the applicationName.localizedLowercase var? I'm hoping that will match the window name.

![CleanShot 2024-06-25 at 23 21 34@2x](https://github.com/ejbills/DockDoor/assets/78599753/a7978a0e-fc04-44e9-baad-94fd74602423)

**Comment by ejbills** [comment]
I think I fixed it, please try the latest commit on main.

**Comment by ShlomoCode** [comment]
Yes, it works!

**Comment by ejbills** [comment]
Thank you for your help!

**Comment by ShlomoCode** [comment]
About [this](https://github.com/ejbills/DockDoor/commit/34c60767062ed15e90be5e90626ad9b55babfd87#diff-c931309a41afa07c65694332ff386d695988445f542bcd1d766eec1af6a16241R262), we can get the bundle directly using `NSWorkspace.shared.urlForApplication` property:
```swift
func getNonLocalizedAppName(forBundleIdentifier bundleIdentifier: String) -> String? {
      guard let bundleURL = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleIdentifier) else {
          return nil
      }
  
      let bundle = Bundle(url: bundleURL)

// ....


let nonLocalName = getNonLocalizedAppName(forBundleIdentifier: app.bundleIdentifier)
```

This seems to me more clean than going through `NSRunningApplication.runningApplications`

**Comment by ShlomoCode** [comment]
If you want I can also make a PR.

**Comment by ejbills** [comment]
Yes, that would be great!

**Comment by ShlomoCode** [comment]
https://github.com/ejbills/DockDoor/pull/28
