### ISSUE TITLE
Support for macOS Ventura

### ISSUE THREAD

**Issue by tech189** [ejbills/DockDoor#211]
Hi, would love to try this app but sadly I'm stuck on macOS Ventura. There was some mention that it might be possible to bring support to it at some point but I thought it would be good to track it in an issue.

For reference: https://old.reddit.com/r/macapps/comments/1dnfnj8/dockdoor_a_free_and_open_source_dock_peeking/la3zgh0/
> Hi, current version is macos 14 min. I will be looking at lowering that requirement - stay posted.

> Default swift package iirc depends on a swift language minimum which is incompatible with Monterey

**Comment by illavoluntas** [comment]
I think DockDoor uses a new macOS API to capture the previews of windows whose minimum requirement is **macOS 14 (*Sonoma*)**. So for now it wouldn't work in macOS Ventura...

**Comment by mehapps** [comment]
I thought the new screen capture api was ventura? could be wrong

**Comment by illavoluntas** [comment]
Well, I don’t know exactly what API DockDoor uses. Maybe @ejbills could answer that.

**Comment by ShlomoCode** [comment]
We use [`SCScreenshotManager.captureImage`](https://developer.apple.com/documentation/screencapturekit/scscreenshotmanager/4251334-captureimage) which is macOS 14.0 and above, but [here](https://developer.apple.com/videos/play/wwdc2022/10156/) there seems to be an alternative syntax that works in macOS 13
