### ISSUE TITLE
Feature Request: Fade away and Delay settings for Hover Preview

### ISSUE THREAD

**Issue by jacobcassidy** [ejbills/DockDoor#212]
I was thinking that a great feature would be if the preview had a setting to delay how long it stays around before disappearing when leaving the dock, or even a fade-out effect that can still be activated by hovering over it before it fades out. 

This will be helpful for those who use auto hide/show for the dock so they don't have to make the preview edge right up to the dock to be able to select the hover previews

**Comment by ejbills** [comment]
Will look into this!
