### ISSUE TITLE
When I set Dock to automatically hide, it seems it is not working.

### ISSUE THREAD

**Issue by chunyang-wen** [ejbills/DockDoor#213]
When I set the Dock to automatically hide, it is not working. When I move my mouse, all the windows disappear.

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/96b8842d-c9d5-4039-a404-c8de896a6db0">

I create two snapshots. The gap for the two case is different.

- The left: Automatically hide
- The right: not hide

**Comment by ejbills** [comment]
Please go into the settings, and in general, go to 'Window Buffer' and try to decrease it until there is no gap between the dock and the window. This should solve your issue.

**Comment by chunyang-wen** [comment]
Thanks, I will try it out.
