### ISSUE TITLE
Updating Dock Door Reverts App Title Style

### ISSUE THREAD

**Issue by the-0verlord** [ejbills/DockDoor#215]
After every update, the setting for the app title style reverts from "embedded" to "default." It's annoying to change back each time. This is not true for something like the window size setting, which stays the same all the time.

**Comment by ShlomoCode** [comment]
Does this happen **every** update?
I think it only happens when we sometimes change the setting scheme. It's unfortunate but DockDoor is still immature and in active development, so it's naturally

**Comment by chrisharper22** [comment]
Yeah, this has been an anticipated issue. We are aware of this. While changing stuff around, no migration system has been used.

**Comment by ShlomoCode** [comment]
Unfortunately the Defaults package does not support migrations https://github.com/sindresorhus/Defaults/issues/29

**Comment by ejbills** [comment]
I'm closing this for now, @the-0verlord the setting shouldn't be modified again anytime soon - so you won't continue to experience your issue. Just know that if we shift around any settings, it's possible we reset some options.
