### ISSUE TITLE
Option to disable Alt-tab functionality

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#22]
I like the peek functionality, but for alt+tab I still prefer to use [alt-tab](https://github.com/lwouis/alt-tab-macos) which is more mature and has more features and customization. Please add an option to disable this option and stick with just the Dock peek.

**Comment by ShlomoCode** [comment]
Actually an implementation of https://github.com/ejbills/DockDoor/issues/11 will solve this problem, because I can set a complex keyboard shortcut like Ctrl + Cmd + Optoion + Shift + F

**Comment by ejbills** [comment]
Closing as this is a duplicate, this feature will be coming soon :)
