### ISSUE TITLE
Window Image Cache

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#223]
@ejbills Why do we actually need it? Did you find that the task of taking screenshots is actually a particularly heavy task?

**Comment by ejbills** [comment]
Yes, the cache was initially a solution to UI hitching as a result of frequent images. Particularly, when the dock is scrubbed in quick succession. 

Also, the cache serves more purposes than just to boost performance. It is a workaround for the screen record notification that shows up in the menu bar.
