### ISSUE TITLE
Hide on menu bar setting

### ISSUE THREAD

**Issue by ilMagnifico** [ejbills/DockDoor#23]
Adding this setting in order to let the app be hidden on menu bar

**Comment by skynet01** [comment]
plus one for this one, maybe it can be a settings extension? My toolbar is already filled to the brim

**Comment by ShlomoCode** [comment]
In the meantime you can use [Hidden Bar](https://github.com/dwarvesf/hidden)

**Comment by skynet01** [comment]
well i just need to hide this one, kind of silly to install an entire app just to hide one icon. But thank you for the link ill keep it in mind. Hope this will get implemented.

**Comment by ejbills** [comment]
Added in v1.0.10.
