### ISSUE TITLE
[BUG just stops working sometimes

### ISSUE THREAD

**Issue by arturasvlt** [ejbills/DockDoor#230]
Hi. So I have MBP14 M3 pro. Whenever the dockdoor works - it's working fine. However, sometimes it just does not show any previews, and when i try to run the DockDoor app itself - nothing really happens. I need to kill the app in the task manager and re-open it.

**Comment by ejbills** [comment]
Is this like, after it's been running for a while? Please use the bug template that is provided, need more info.

**Comment by yossizahn** [comment]
@ejbills Just throwing out an idea: The OS may be disabling the event tap because it's deemed unresponsive for some reason.
I would suggest listening for `kCGEventTapDisabled` event.

**Comment by ejbills** [comment]
Thanks @yossizahn - closing this issue for now. @arturasvlt please feel free to re-open with more details with the bug report format.
