### ISSUE TITLE
[BUG] Window Preview showing Safari Downloads as a window when download list is open

### ISSUE THREAD

**Issue by binaryblitz10** [ejbills/DockDoor#232]
## Describe the bug
If I have the downloads list open and preview Safari on Dock, it shows the downloads list as a safari window.

## Screenshots

![Screenshot 2024-07-25 at 11 37 00 PM](https://github.com/user-attachments/assets/ac910dd5-dbb7-49d9-ac21-af44761d9c08)

## Environment
 - macOS version: Sonoma 14.5
 - App version: 1.1.4

**Comment by hasansultan92** [comment]
Hi @binaryblitz10, there are new features coming to this application including support of navigating to windows in other spaces, this bug will not exist in that revision of the application.
