### ISSUE TITLE
Don't close dockdoor unless the user moves thier cursor away (it does so when I click the red X buttons)

### ISSUE THREAD

**Issue by YousufSSyed** [ejbills/DockDoor#233]
When I click the red x button to close a window, dockdoor closes and I have to hover over the app icon again to close another window, this makes closing multiple windows time consuming.

**Comment by ShlomoCode** [comment]
In the meantime you can use the purple button 🟣, it quits the application which closes all its windows.

**Comment by ejbills** [comment]
this will be in the next version. i am combining this issue with https://github.com/ejbills/DockDoor/issues/372
