### ISSUE TITLE
[BUG] Several "windows" showing up for Adobe Lightroom Classic

### ISSUE THREAD

**Issue by 0x5b62656e5d** [ejbills/DockDoor#239]
## Describe the bug
When Adobe Lightroom Classic has a catalog opened, the panels in LrC show up as different windows in DockDoor

Adobe applications have windows that do not have traffic light buttons. 

## Steps to reproduce
- Open Adobe LrC and open a catalog with photos
- Alt + Tab (or other binds) to activate Dockdoor switcher

## Expected behavior
Only 1 window is supposed to show up in Dockdoor

## Actual behavior
"Windows" resembling the control panels in LrC show up as windows

## Screenshots
![IMG_1133](https://github.com/user-attachments/assets/6e61e730-23ca-4c64-8e45-3282750764e7)

## Environment
 - macOS version: Sonoma 14.5
 - App version: 1.1.5
 - Adobe Lightroom Classic: 13.4 Release, Camera Raw 16.4, Build [202406181129-60d181b7]

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by hasansultan92** [comment]
Is this happening when the application is in full screen mode?

**Comment by 0x5b62656e5d** [comment]
Yes. Panels still show up as "windows" in fullscreen.

**Comment by 0x5b62656e5d** [comment]
Panels show up as windows in both fullscreen and non-fullscreen mode.

**Comment by 0x5b62656e5d** [comment]
![image](https://github.com/user-attachments/assets/97a3c468-2449-449e-9b29-cc4b7461e692)

Multiple windows without titles being captured from Adobe Lightroom

(Debugged with Hasan)
