### ISSUE TITLE
[BUG] No traffic light buttons on Adobe InDesign & Illustrator

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#244]
Adobe InDesign and Adobe Illustrator do not show traffic light buttons.

## Steps to reproduce
- Open Adobe InDesign or Adobe Illustrator and hover the icon.

## Screenshots
![Capture d’écran 2024-08-06 à 12 13 40](https://github.com/user-attachments/assets/a6c78429-e381-48f9-81a7-ed100fbd21f8)
![Capture d’écran 2024-08-06 à 12 21 00](https://github.com/user-attachments/assets/dd9ac085-aa32-4ba8-8548-0ce0ecc02c0c)

## Environment
 - macOS version: macOS Sonoma 14.5
 - App version: 1.1.5
 - Adobe InDesign 2024
 - Adobe Illustrator 2023

## Additional context
Other Adobe products such as Photoshop and Acrobat do show up traffic light buttons.
All the settings were set to show up the buttons. The windows presented were active (**not** minimized). Here are Photoshop and Acrobat for comparison.
![Capture d’écran 2024-08-06 à 12 17 34](https://github.com/user-attachments/assets/e4666f25-4cfc-48d6-9fb1-1bf3aef16c08)
![Capture d’écran 2024-08-06 à 12 22 06](https://github.com/user-attachments/assets/af6b0ea2-b9ee-4137-b560-482c745eb399)

Photoshop and Illustrator do not show a title because they are on home screen (which does not have any title).
I think Adobe software are known to behave *buggily* with other apps (Rectangle struggles with Adobe windows).

**Comment by ejbills** [comment]
If they don't appear, it's because the app failed to find any associated accessibility elements for that given window's buttons (like the close button, minimize, etc. all have their own accessibility element). I will take a look at this, but since you mentioned other apps also have issues with adobe, it might just be that they are properly creating their windows.

**Comment by illavoluntas** [comment]
I noticed Adobe’s traffic light buttons are slightly different than other apps, so they might use their own buttons and UI… But it is still strange that DockDoor is able to detect Photoshop’s buttons but not InDesign’s or Illustrator’s.

**Comment by ejbills** [comment]
Duplicated https://github.com/ejbills/DockDoor/issues/244

**Comment by illavoluntas** [comment]
> Duplicated #244

What do you mean?

**Comment by ejbills** [comment]
> > Duplicated #244
> 
> What do you mean?

I pasted the wrong link, I updated it now. I am combining this issue with the other one as all adobe applications have this issue, and they are related.
