### ISSUE TITLE
[BUG] macOS Sequoia 15.0 - old API causes DockDoor to ask about screen and audio recording? (ScreenCaptureKit)

### ISSUE THREAD

**Issue by Traiver** [ejbills/DockDoor#245]
## Describe the bug
DockDoor (as of version 1.1.5) is asking for screen and audio recording with every new app that you open, as soon as you boot up your Mac.

## Steps to reproduce
- Boot up your Mac with macOS Sequoia 15.0 (recording this behaviour with 15.0 Beta (24A5298h))
- Dockdoor needs to be active in the background
- Open new apps. With every new app opened, a new popup screen appears asking for screen and audio recording, if you do not allow it directly on the first popup

## Expected behavior
The app already has access to screen and audio recording in the system settings. It shouldn't ask if the app is allowed to use it furthermore. Could be caused through the old API used for this app but unsure here. Several apps on macOS Sequoia have this problem and Apple is already informed about it.

## Screenshots
Screenshots of these popups can be find below.
<img width="1031" alt="Bildschirmfoto 2024-08-07 um 17 50 02" src="https://github.com/user-attachments/assets/ad772a7f-6914-4ca1-ae9f-bf910c0c040a">
<img width="762" alt="Bildschirmfoto 2024-08-07 um 17 51 59" src="https://github.com/user-attachments/assets/a39c663a-cc4f-48ed-92d4-209443417f86">

## Environment
 - 15.0 Beta (24A5298h)
 - App version: [1.1.5]

- [ x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
That's a new one... this is the latest seqouia beta?

DockDoor uses the new screen recording API, btw.

**Comment by Traiver** [comment]
This was on Sequoia Beta 4. I updated to Sequoia Beta 5 a few minutes ago and the behaviour changed. Seems like these popups don't appear anymore as soon as I open a new application. I wonder what will happen after bypassing this for a week now. Maybe the popup appears and will ask to bypass the system private window picker again. Though I just wanted to let you know. :)

<img width="699" alt="Bildschirmfoto 2024-08-07 um 18 17 51" src="https://github.com/user-attachments/assets/e23e120c-3bf7-432b-a4ef-52f513dc74a8">

**Comment by illavoluntas** [comment]
Seems a new feature from macOS 15. 

https://forums.appleinsider.com/discussion/237241/users-have-to-confirm-screen-recording-permission-every-week-in-macos-sequoia

https://9to5mac.com/2024/08/06/macos-sequoia-screen-recording-privacy-prompt/

**Comment by ejbills** [comment]
That is a new message, we will have to see what Apple decides on before we can make any concrete assumptions about how to handle this.

**Comment by hasansultan92** [comment]
This is normal @ejbills @Traiver, Almost anytime I run the application or build and compile the application I get a bunch of these popups. Something they have added with Mac OS Sequoia 

https://www.reddit.com/r/mac/s/PdaoFFZlk6

**Comment by illavoluntas** [comment]
There is a temporary workaround (I didn’t test it as I don’t use macOS Beta) but it is not related to the app. 
https://www.reddit.com/r/mac/comments/1dqfmii/macos_15_beta_if_youre_having_issues_with_app_can/

**Comment by hasansultan92** [comment]
Yes, its still a hit or miss. Likely Apple will patch this work around sooner than later

**Comment by illavoluntas** [comment]
I think this issue can be closed as not planned. It is a big problem coming from Apple, not from DockDoor, and there is nothing we can do to bypass these alerts.
