### ISSUE TITLE
[BUG] Dock Previews NOT showing for iOS/iPadOS apps installed on Apple Silicon Macs

### ISSUE THREAD

**Issue by stevehoek** [ejbills/DockDoor#247]
## Describe the bug
Dock Previews NOT showing for iOS/iPadOS apps installed on Apple Silicon Macs

## Steps to reproduce
- Install latest X/Twitter app from App Store
- Launch it
- See no dock preview

## Expected behavior
A dock preview of the app's window

## Actual behavior
No dock preview

## Screenshots
<img width="192" alt="image" src="https://github.com/user-attachments/assets/c4ffe9c1-f248-450c-b9cb-41557a7555ca">

## Environment
 - macOS version: Sonoma 14.6.1
 - App version: 1.1.5

## Additional context

- [x ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ShlomoCode** [comment]
now showing or **not** showing?...

**Comment by stevehoek** [comment]
> "now showing" or **not** showing?...

Sorry, NOT
I edited the bug report

**Comment by ShlomoCode** [comment]
@stevehoek I tested in the latest stable version of DockDoor with 2 apps ([AnyTracker](https://apps.apple.com/us/app/anytracker-track-anything/id6450756953) Designed for iPhone and [FortiClientVPN](https://apps.apple.com/us/app/forticlient-vpn/id1475674905) Designed for iPad) and it worked. Is this a specific issue with the Twitter app?

Also, make sure you are on the latest version of DockDoor (currently is 1.1.5)

**Comment by stevehoek** [comment]
@ShlomoCode yes, using latest version.  Not specific to X... also happens for me on these apps: eero, Weather Underground, Tautulli, Sensibo, Quora, Plex Dash, Audible, Eve... in fact not one iOS/iPadOS app that I have installed on my MBP M3 shows the dock preview correctly.

**Comment by ShlomoCode** [comment]
I tested with Quora app, works great.

**Comment by illavoluntas** [comment]
Works with ARTE (TV app in Germany/France) designed for iPad/iOS and it worked

**Comment by ejbills** [comment]
I am also unable to reproduce this, are you sure you're using the latest version?

**Comment by stevehoek** [comment]
After a restart, it seems to be working.
