### ISSUE TITLE
docs: Improve web communication and documentation

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#257]
I’ve noticed that some repositories have localized README.md files, which could be useful for non-English speakers. Even though the majority of GitHub users speak English more or less fluently, it might still be helpful.

I came across this simple example (https://github.com/jonatasemidio/multilanguage-readme-pattern) that looks quite interesting. I can take care of this new feature if the development team is okay with it (fork + PR for the pattern in main README.md, then ShlomoCode could translate in Hebrew if they want).

**Comment by ShlomoCode** [comment]
I think it's better to create a nice landing page and locale it

**Comment by illavoluntas** [comment]
Currently there is a index.html but it seems outdated. I can also update it if needed.

**Comment by ShlomoCode** [comment]
Yes i think it's just the default Jekyll theme

**Comment by illavoluntas** [comment]
Website is hosted on https://dockdoor.kepler.cafe/

**Comment by ShlomoCode** [comment]
It's just CNAME to GitHub Pages
https://github.com/ejbills/DockDoor/blob/main/CNAME

**Comment by illavoluntas** [comment]
Oh, OK, I didn’t know about it. Thanks for the information.

**Comment by illavoluntas** [comment]
> Yes i think it's just the default Jekyll theme

Looking at the index.html, the styles are integrated with <style> on the header. I don't know much about Jekyll themes, is that a characteristic way styles are applied with them?

**Comment by illavoluntas** [comment]
@ShlomoCode I'm making slight changes in wording in README.md that will be applied to the brand new index.html. Does README.md has to be updated consequently or does it have to point to the new index.html ? Or give minimal information?
I'm also thinking to use https://dockdoor.kepler.cafe instead of GitHub docs because it is easier to get a more beautiful result. Also, using GitHub docs would remain the same as README.md as it uses Markdown as well, thus abandoning your idea of a landing page or something similar.

**Comment by ShlomoCode** [comment]
Again, dockdoor.kepler.cafe is simply [github pages with a custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site).

In general, GitHub pages can do 2 things:
- Render a static website (HTML CSS JS files)
- Render each markdown file as HTML, using a built-in tool called Jekyll, for example:
https://github.com/ejbills/DockDoor/blob/main/CHANGELOG.md -> https://dockdoor.kepler.cafe/CHANGELOG.html
(There specifically I include the design directly using a style tag but the correct way is to define a design using a theme)

If we don't plan to do a special design but only formatted text, there is no point in maintaining two Readme pages, one md and one html, and we can save only README.me, and load it as the landing page with added style using a Jekyll theme.

**Comment by ShlomoCode** [comment]
I don't see in #258 anything that can't be done with markdown + CSS

**Comment by illavoluntas** [comment]
My idea is just to have a web page (GitHub pages) available for locales and large diffusion (so that users do not have to consult GitHub repo). I just think HTML and CSS fit better for styling and controlling video playback (better quality than GIF).

**Comment by ShlomoCode** [comment]
You can insert a <video> tag in markdown as well...
If you plan to invest in design and make something beautiful that is not possible with markdown, rather. This is not the case at the moment.

**Comment by illavoluntas** [comment]
OK, we’ll see @ejbills’s point of view. Anyway, I don’t think we would have to update very frequently README.md or index.html so it wouldn’t be a big deal having both.

**Comment by ejbills** [comment]
I'm in favor of a prettier site, so let's have the site and the README separate. The current github pages is a placeholder.

**Comment by illavoluntas** [comment]
> I'm in favor of a prettier site, so let's have the site and the README separate. The current github pages is a placeholder.

I’m trying a temporary design, inspired from ancient index.html. I suppose you want something prettier? 
See https://illavoluntas.github.io/dockdoor, change CSS link rel in `<header>` to "/dockdoor/assets/styles.css".

**Comment by ejbills** [comment]
> > I'm in favor of a prettier site, so let's have the site and the README separate. The current github pages is a placeholder.
> 
> I’m trying a temporary design, inspired from ancient index.html. I suppose you want something prettier? See https://illavoluntas.github.io/index2, change CSS link rel in `<header>` to "/DockDoor/assets/styles.css".

Apologies that I didn't get to this post till now. I just checked out https://illavoluntas.github.io/index and it looks AMAZING!

**Comment by illavoluntas** [comment]
> > > I'm in favor of a prettier site, so let's have the site and the README separate. The current github pages is a placeholder.
> > 
> > 
> > I’m trying a temporary design, inspired from ancient index.html. I suppose you want something prettier? See https://illavoluntas.github.io/index2, change CSS link rel in `<header>` to "/DockDoor/assets/styles.css".
> 
> Apologies that I didn't get to this post till now. I just checked out https://illavoluntas.github.io/index and it looks AMAZING!

No problem, thank you for the feedback! There were some challenges but I think it is done for now.
Still, I have to figure out a way to add contributive translations (I was thinking about Crowdin) and set up the wiki (for documentation, even though I think it will be light). Documentation wiki started at https://dockdoor.miraheze.org, it might be interesting if you created an account there (this system is similar to Wikipedia) so that I can set your permissions (administrator).

**Comment by ShlomoCode** [comment]
Yes, nice job!
@ejbills How about a domain name more suitable for branding and sharing? Something like dockdoor.com

**Comment by illavoluntas** [comment]
I agree too, because .kepler.cafe does not seem very serious / relevant for a software.

**Comment by illavoluntas** [comment]
However, .com tend to be very expensive. You have to choose something reasonable.

**Comment by ShlomoCode** [comment]
It's only $10.44/year fixed price on Cloudflare

**Comment by ejbills** [comment]
Did someone snipe it? I would prefer to own any official DockDoor related domains.

**Comment by illavoluntas** [comment]
I didn’t. Don’t know who owns dockdoor.com

**Comment by ShlomoCode** [comment]
It seems to have been registered long before dockdoor was born :)

![CleanShot 2024-08-22 at 21 54 20@2x](https://github.com/user-attachments/assets/b20ddac7-22e5-4523-a31c-3f8b3741268e)

**Comment by ejbills** [comment]
I bought dockdoor.net, however I don't think github pages can be at the zone apex of a domain, correct me if I'm wrong.

**Comment by illavoluntas** [comment]
Nice!

**Comment by illavoluntas** [comment]
I will continue tomorrow (maybe ejbills’s tonight). Can you change CNAME?

**Comment by illavoluntas** [comment]
> I bought dockdoor.net!

Will you give up https://dockdoor.kepler.cafe?

**Comment by ejbills** [comment]
> > I bought dockdoor.net!
> 
> Will you give up https://dockdoor.kepler.cafe?

Yep, check it out: https://dockdoor.net/

**Comment by ShlomoCode** [comment]
@ejbills Note that we still need to keep https://dockdoor.kepler.cafe/appcast.xml alive, otherwise checking for updates from within the app won't work and all users will be stuck on the current version unless we manually update from GitHub:
![CleanShot 2024-08-23 at 00 25 06@2x](https://github.com/user-attachments/assets/7b5de6b3-8fe2-463a-a345-516c6c60b0b4)

**Comment by ejbills** [comment]
> @ejbills Note that we still need to keep https://dockdoor.kepler.cafe/appcast.xml alive, otherwise checking for updates from within the app won't work and all users will be stuck on the current version unless they manually update from GitHub: ![CleanShot 2024-08-23 at 00 25 06@2x](https://private-user-images.githubusercontent.com/78599753/360672442-7b5de6b3-8fe2-463a-a345-516c6c60b0b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjUyNDYsIm5iZiI6MTcyNDM2NDk0NiwicGF0aCI6Ii83ODU5OTc1My8zNjA2NzI0NDItN2I1ZGU2YjMtOGZlMi00NjNhLWEzNDUtNTE2YzZjNjBiMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIyMTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYjI2ZjVhMDYzYThlZjdiN2Y5NGU5ZDE3ZTNhYjkyNTk2YWQzNzk1ODJmYWEwYmIxZDY3MjEzMzUzOWYzNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEHVKPsSgW8FIhSFtwE85rs3stPrkclgdOMkm8nnt9M)

Oh yes, thanks for catching that. I just setup domain forwarding, so it should be fine.

**Comment by ShlomoCode** [comment]
@ejbills The critical point is that existing installations can find the new update (using sparkle). And right now it seems it's still returning the same error, maybe because of the SSL thing.

You can do it with an external provider like Vercel, Netlify or Render,
Or you can also just create another, empty, temporary repo with the appcast.xml file and associate dockdoor.kepler.cafe with it

**Comment by ejbills** [comment]
> @ejbills The critical point is that existing installations can find the new update (using sparkle). And right now it seems it's still returning the same error, maybe because of the SSL thing.
> 
> You can do it with an external provider like Vercel, Netlify or Render, Or you can also just create another, empty, temporary repo with the appcast.xml file and associate the dockdoor.kepler.cafe domain with it

The redirect is working within my app, no more update error. I suspect you're now facing a caching issue.

**Comment by ShlomoCode** [comment]
Yes now it works!
How did you actually do the redirect?

**Comment by ejbills** [comment]
> Yes now it works! How did you actually do the redirect?

I use porkbun to manage my domains, they have been great since google domains shut down. Porkbun offers a free domain forwarding service. Took me 2 minutes!

**Comment by illavoluntas** [comment]
> @illavoluntas I think it's worth applying a bit of border-radius here ![CleanShot 2024-08-23 at 16 16 29@2x](https://private-user-images.githubusercontent.com/78599753/360939418-7a9e82b0-365d-4db7-b14d-1a7b1ba5194c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzMyNTUsIm5iZiI6MTcyNDQzMjk1NSwicGF0aCI6Ii83ODU5OTc1My8zNjA5Mzk0MTgtN2E5ZTgyYjAtMzY1ZC00ZGI3LWIxNGQtMWE3YjFiYTUxOTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE3MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMGZiMWZiZDY0OWI1ZWFkZTgwZDI4MDk2ZDljNzVhYzg5NjE0YzVlMGVmN2NjOWQ1NmZhMTAyZmYxNWI4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gd7ZktZ-qrCgi96yw39MLI4f3bLlXSoL5z0LhfHRDA8)

Agreed 👍. I will add this tomorrow

**Comment by illavoluntas** [comment]
@ejbills @ShlomoCode, I have created a documentation wiki for DockDoor at https://dockdoor.miraheze.org/. Even though there won’t be tons of content, it might still be useful (in order to extend the FAQ for example). 
If you agree with this, could each of you please create an account for that wiki so that I can set up administrator permissions for you? Probably usernames "Ejbills" and "ShlomoCode" would work, but you can also choose your own usernames, just notify me 😉

**Comment by illavoluntas** [comment]
> @illavoluntas I think it's worth applying a bit of border-radius here ![CleanShot 2024-08-23 at 16 16 29@2x](https://private-user-images.githubusercontent.com/78599753/360939418-7a9e82b0-365d-4db7-b14d-1a7b1ba5194c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjEzNDksIm5iZiI6MTcyNDUyMTA0OSwicGF0aCI6Ii83ODU5OTc1My8zNjA5Mzk0MTgtN2E5ZTgyYjAtMzY1ZC00ZGI3LWIxNGQtMWE3YjFiYTUxOTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3MzcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YmYxNGY4Y2JmMmMxODQ3ZjI0ZDgyODBkMzAzNTcyNDk3NTNkZGUzNTE4YTc4YjNmMWYxN2ZhN2IwZGI3ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QjAW44xtHGBP9oxwSFnCh4j5vRwxlE2VNy1_Jq1lBw)

@ShlomoCode I applied 10px border radius for FAQ box, what do you think about it?

![image](https://github.com/user-attachments/assets/65caf897-1ec5-4d73-8f92-98134164dc27)

**Comment by illavoluntas** [comment]
Besides, https://crowdin.com/project/dockdoornet/invite?h=86625f90ecb8ba6203441ccc5c91b33f2190817 is the link for localization of the website. It will remain updated by myself (or someone of the team, just **not automatically**) as the strings might get dangerous if someone decides to put some malicious JavaScript code in there.

**Comment by ShlomoCode** [comment]
@illavoluntas Is the github built-in wiki not enough?

**Comment by ShlomoCode** [comment]
> (or someone of the team, just **not automatically**) as the strings might get dangerous if someone decides to put some malicious JavaScript code in there.

We just need to pass the translations sanitizing or escaping.

**Comment by illavoluntas** [comment]
> @illavoluntas Is the github built-in wiki not enough?

I’ve been thinking about it again, and finally I think GitHub pages is better for a localized wiki than GitHub wiki or the wiki I created. GitHub wiki makes it hard to localize it, as GitHub pages is more flexible

**Comment by illavoluntas** [comment]
> > (or someone of the team, just **not automatically**) as the strings might get dangerous if someone decides to put some malicious JavaScript code in there.
> 
> We just need to pass the translations sanitizing or escaping.

How would you do that?

**Comment by ShlomoCode** [comment]
> > @illavoluntas Is the github built-in wiki not enough?
> 
> I’ve been thinking about it again, and finally I think GitHub pages is better for a localized wiki than GitHub wiki or the wiki I created. GitHub wiki makes it hard to localize it, as GitHub pages is more flexible

I don't think a wiki needs localization. A wiki is kind of "for advanced use cases", and Google Translate should be enough for it.

**Comment by illavoluntas** [comment]
> > > @illavoluntas Is the github built-in wiki not enough?
> > 
> > 
> > I’ve been thinking about it again, and finally I think GitHub pages is better for a localized wiki than GitHub wiki or the wiki I created. GitHub wiki makes it hard to localize it, as GitHub pages is more flexible
> 
> I don't think a wiki needs localization. A wiki is kind of "for advanced use cases", and Google Translate should be enough for it.

You’re right, often advanced users also speak English more or less fluently as most of advanced documentation is in English. 

However, my idea was to add things like term explaining which does need localization.

**Comment by ShlomoCode** [comment]
I didn't fully understand what "term explaining" means, but if it is intended for the simple user it can be on the website, can't it?

**Comment by illavoluntas** [comment]
> I didn't fully understand what "term explaining" means

I meant that we could explain some vocabulary used in DockDoor, such as "Window buffer". For example, in French, the term used is specific to technology and graphical computing, and I don’t think there are meaningful synonyms, so it would be better to just explain it further. 


> but if it is intended for the simple user it can be on the website, can't it?

Agreed, I meant that here: https://github.com/ejbills/DockDoor/issues/257#issuecomment-2308493508.

**Comment by ShlomoCode** [comment]
I think it is better to add a help tip under the control in the settings that will explain the role of the control, which will be localizable

**Comment by illavoluntas** [comment]
You could try adding one help button (https://developer.apple.com/documentation/appkit/nsbutton/bezelstyle/helpbutton) by tab

**Comment by illavoluntas** [comment]
> I think it is better to add a help tip under the control in the settings that will explain the role of the control, which will be localizable

Oh, didn’t see your comment.

**Comment by illavoluntas** [comment]
The help button could link to the simplified documentation located at https://dockdoor.net.

**Comment by ShlomoCode** [comment]
> > > (or someone of the team, just **not automatically**) as the strings might get dangerous if someone decides to put some malicious JavaScript code in there.
> > 
> > 
> > We just need to pass the translations sanitizing or escaping.
> 
> How would you do that?

sanitizing - DOMPurify libery etc.
escaping - `innerText` instead of `innerHTML` (will not allow any html tags in translation)

**Comment by illavoluntas** [comment]
I think sanitizing is not enough — if there is vandalism it might be detected manually by quickly translating using AI or Google Translate. This way we can also check for malicious code. 

`innerHTML` is needed for styling, such as `<strong>` tags or `<a>`.

**Comment by illavoluntas** [comment]
But I understand automation is way better for long term use.

**Comment by ShlomoCode** [comment]
> I think sanitizing is not enough

Why? This is absolutely best practices. Malicious code should not be detected, as sanitization will not allow any script insertion. I trust an industry leading library more than my manual identification over the years. See https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model

**Comment by illavoluntas** [comment]
Is it not better that @ejbills creates a dedicated repository for the website? This compromises less the DockDoor repository and organises files a better way. This way, ejbills can implement cleanly the code sanitizing system without interfering with application files.

**Comment by illavoluntas** [comment]
> > I think sanitizing is not enough
> 
> Why? This is absolutely best practices. Malicious code should not be detected, as sanitization will not allow any script insertion. I trust an industry leading library more than my manual identification over the years. See https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model

Agreed. I looked further about DOMPurify and I will add the JavaScript code today.

**Comment by illavoluntas** [comment]
> a ready and tried library, there are many out there and usually they will support Vanilla JS/jquery as well

I don't understand about what library you mean, it is about localization files?

**Comment by ShlomoCode** [comment]
Yes. You don't need to implement your own translation format and parser.

**Comment by illavoluntas** [comment]
Like [i18next](https://github.com/i18next/i18next-parser)?

**Comment by ShlomoCode** [comment]
Yes

**Comment by illavoluntas** [comment]
Is i18next supported by GitHub pages? It needs dependencies and CLI installation.

**Comment by illavoluntas** [comment]
Thank you Shlomo for your advice :1st_place_medal:! I will try to implement this on my test server, then try it on https://illavoluntas.github.io.

**Comment by illavoluntas** [comment]
Added! I still have to correct a bug with DOMPurify but I think it works. Thanks again Shlomo!

**Comment by illavoluntas** [comment]
I tried adding Crowdin automation for testing purposes on my fork, but it does not seem to recognize the JSON files, only the Localizable.xcstrings. I think this is better if ejbills creates a dedicated repository for the website.

**Comment by illavoluntas** [comment]
Well, first of all, I will create a test repository, and if it is successful, I will transfer ownership to ejbills.

**Comment by illavoluntas** [comment]
Oh, I think this is crowdin.yml which interferes with automation.

**Comment by illavoluntas** [comment]
<img width="375" alt="image" src="https://github.com/user-attachments/assets/b2ad4463-91ca-4529-bce3-c783f7ec00b1">

@ShlomoCode Is the contrast sufficient in dark mode?

**Comment by ShlomoCode** [comment]
Yes

**Comment by illavoluntas** [comment]
Does dark mode work for both of you? Just click the button with 🌙 or ☀️. It didn’t work for me on iOS 15.8.3 (dark mode isn’t toggled).

**Comment by illavoluntas** [comment]
@ejbills Hi, could you please add https://dockdoor.net to the about section of the repository?https://stackoverflow.com/questions/67217281/adding-github-pages-url-to-github-repositorys-about-section

**Comment by illavoluntas** [comment]
@ejbills What is your opinion about my new README.md (https://github.com/illavoluntas/illavoluntas.github.io)?
