### ISSUE TITLE
Dock peek: dock icons overlap preview pop-up window

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#26]
Dock icons overlap the pop-up and obscure some of its content. The issue is especially bad if an app has a minimized window; the dock peek for the app (showing the title of the minimized window) is almost entirely blocked by the dock icon. How much the pop-up is obscured by the dock icon depends on the dock icon size and magnification set in System Preferences. 

Suggest that the bottom edge of the preview pop-up always be aligned just above the top of dock icons. Possibly this could be a user-defined setting.

**Comment by ejbills** [comment]
This will be in the next release, it will be a setting called "Window Buffer".
