### ISSUE TITLE
[FR] Make window selection more distinguishable in Window Switcher

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#260]
## Problem or Need
With Window Switcher, detecting the selected window can be very hard, especially when the monitor has low brightness or external light is illuminating the screen.

## Proposed Solution
Make the gradient more pronounced or find another solution to make it easier to find the selected window.

## Screenshots
![Capture d’écran 2024-08-16 à 13 57 02](https://github.com/user-attachments/assets/4ba54386-aa8c-4a65-bbcd-5704fc341a86)
I think the gradient is not obvious enough the attract the attention of the user.

## Potential Impact
Make the app even more accessible to all eye problems and low monitor brightness.

## macOS Version
macOS 14.5 Sonoma

## App Version
1.1.5

- [X] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by illavoluntas** [comment]
Closed issue as completed in 1.1.6. Colors can be customized for more visibility.

**Comment by ejbills** [comment]
How is this? 

https://github.com/user-attachments/assets/66eb450f-e32d-43f6-95ab-6e9f98d03908

**Comment by Q3Defender** [comment]
looks awesome!
