### ISSUE TITLE
[REQUEST] SVG DockDoor icon

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#269]
SVG format is better for web communication (#257, #258), first because it is simply *scalable vector graphics* and second because it is lighter than regular images.

I was wondering if it was possible to get a SVG version of DockDoor icon, as the program @VisualisationExpo uses in #65 is basically vector too.

**Comment by illavoluntas** [comment]
I am reiterating this demand for the new icon. @ejbills Are there plans for an SVG version of DockDoor? That’s nearly impossible the designer used an image editor, rather a vector editor, so there are possibilities for SVG.

**Comment by VisualisationExpo** [comment]
I will honor your request if there's a promise not to alter the file without letting me or the author of DockDoor know. Esssentially you'll be getting the editable version that I made using Sketch and could potentially be included on Linux sites with no context and then it's out of my hands.

I've thought about it quite a bit and if it's for web communication? Like on the repo?

Just asking questions 😄

**Comment by illavoluntas** [comment]
Well, see #258 and https://illavoluntas.github.io. This is the demonstration website of my work at the current time, it’s basically a GitHub pages website, whose source code is publicly available. The SVG icon would be included in the DockDoor original repository. At any time you can check on the *originality* of your work, essentially the DockDoor icon is used 1 time in the website. 

I don’t know your opinion about that; and it’s you and only you decide. However, after some reconsideration, it might not be worth it as there is only minimal use of the icon and we already have high quality PNG icons. 

Anyways, I will assure that your work will not be modified — that is absolutely not my intent. But consider this request as a low priority one; I had other plans for the use of this icon, but now it is very minimal.

**Comment by illavoluntas** [comment]
Nevermind @VisualisationExpo, don't bother yourself :wink:
Thank you for answering, but I feel like the SVG icon isn't needed anymore and adding it to an open-source website would make your amazing work vulnerable to hijacks and unwanted reproductions and modifications.

Also, the icon is now outdated, it has been replaced with another... Well, thank you anyways! :smile:

**Comment by VisualisationExpo** [comment]
> Nevermind @VisualisationExpo, don't bother yourself 😉 Thank you for answering, but I feel like the SVG icon isn't needed anymore and adding it to an open-source website would **make your amazing work vulnerable to hijacks and unwanted reproductions and modifications.**
> 
> Also, the icon is now outdated, it has been replaced with another... Well, thank you anyways! 😄

I feel like that's a diss - I don't like your attitude. Just because I didn't honor your request. Come on..

**Comment by illavoluntas** [comment]
@VisualisationExpo I didn’t want to be aggressive… That might be the way I said it. It was not related to your refusal, and I’m sorry if you took it personally. It’s just that I changed plans, and this SVG icon is not needed anymore… Again, sorry 🙏

**Comment by VisualisationExpo** [comment]
Hi, it's all good. 
Plans change of course.

I was perhaps too quick to write back with my head not properly attached because I never see my work as amazing. 

I like the new icon for DockDoor. You happen to have designed that?

Thank you for replying.

**Comment by illavoluntas** [comment]
> Hi, it's all good. Plans change of course.
> 
> I was perhaps too quick to write back with my head not properly attached because I never see my work as amazing.
> 
> I like the new icon for DockDoor. You happen to have designed that?
> 
> Thank you for replying.

I didn’t design it, I think it’s Kinark (`@Kinark`).  And yeah, I like it too 😀
