### ISSUE TITLE
Enhancement suggestion (dock peek): hover over selects window in preview pop-up

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#27]
I think someone may have suggested this in a previous comment. 

Enhancement suggestion: as a user, I want to hover over a window in the preview pop-up and have the window selected (equivalent to a tap/click) after an interval of time has elapsed. I want a setting that allows me to define the time interval. 

Comment: AFAIK similar apps have this feature. Should also work for minimized apps in dock peek. Not a high priority request, just a nice to have feature. Not sure if this should extend to Ctrl+Tab as well?

**Comment by ejbills** [comment]
hey @0n0mat0p03ia this is in v1.1.2!
