### ISSUE TITLE
[FR] Window Switcher is way too slow

### ISSUE THREAD

**Issue by tmnrdhf** [ejbills/DockDoor#273]
## Problem or Need
Unfortunately the window switcher is extremely slow. I'm currently using AltTab and it is super snappy. I can literally slam down the shortcut and I'm already in the previous window, without even having seen the UI of AltTab. 
With DockDoor nothing even happens when I do that. I have to enter the shortcut, hold the alt-key and wait until the UI comes up eventually. Once that has happened I can then let go to open the previous window. Should I want to cycle to a completely different window the transition is also kinda slow in comparison. For me that makes it unusable in my daily workflow.

## Proposed Solution
Make the window switcher faster and more responsive.

## Potential Impact
Move one more step towards being an alternative to AltTab.

## macOS Version
14.5

## App Version
1.1.5

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by ejbills** [comment]
@MinecraftEarthVillage - not sure what the download link was, or what it did. I am removing it, if you have suggestions on how to implement this feature please share it here. Otherwise, please don't post random download links, just for the safety of users. Hope you understand and thanks.

@tmnrdhf I am working on this!

**Comment by tmnrdhf** [comment]
@ejbills since the last update it is possible to slam down the keyboard shortcut and be in the previous window instantly. Really great, thanks a lot for that! 

However, switching to other windows than the most previous one is still way too slow. On alttab you can press alt + tab e.g. 4 times in a row with high speed and you are directly in the 4th recent window. 

Is there any option to improve the speed for that in DockDoor as well?
