### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by win0202** [ejbills/DockDoor#275]
## Describe the bug
1. It seems like the application cannot display the preview of certain applications such as 'Hancom Office HWP' (Korean Word Program) 
No matter I hide/display the program, it doesn't show the preview regardless of the application's status

2. When I want to search through an excel document (cmd+f), the search window seems to be considered as a new window for dockdoor, so the search window takes a huge screen
I didnt check other document dealing applications btw.

## Steps to reproduce
1. doesnt have steps to reproduce
2. open an excel file,  enter a shortcut to search through the document (cmd+f) and check the preview with dockdoor

## Expected behavior
1. shows the preview of some applications like how dockdoor works for other applications
2. Such windows shouldn't be considered as a new windows and should be in the window where it belongs 
## Actual behavior
as described above

## Screenshots
![Screenshot 2024-08-27 at 17 33](https://github.com/user-attachments/assets/9b857224-6129-4bd5-a2c7-220673a7396d)

## Environment
 - macOS version: 14.6.1  sonoma,  M2 Max Macbook Pro
 - App version: 1.1.5

## Additional context

- [ ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by illavoluntas** [comment]
The Excel part is the same as #36 and #268, developers might add a feature to let user set minimum height and width for window previews.

For the word processor part, it might be the program you use itself who doesn’t build correctly their windows. #163 and #244 are similar, especially #163. Do you have other application names which do not show any preview?

Aside of that, please set a relevant title for your issue. This will help for future mentions and is better for developers too.

**Comment by ejbills** [comment]
Will be fixed in the next version
