### ISSUE TITLE
[FR] Support for macOS Monterey 12.3

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#279]
> Once this PR is merged, does it mean DockDoor will be fully compatible with Ventura at the next release?
> 
Yes, 2 things I have not done at the moment are support for Window Image Resolution Scale and SmoothGradient (the package we use for this is macOS 14 only)

> Does the API used for Ventura work on Monterey? Or is it 13.0+?

I can adapted quite easily to macOS 12.3, the question is how much demand is there for it?

_Originally posted by @ShlomoCode in https://github.com/ejbills/DockDoor/issues/267#issuecomment-2308468169_

**Comment by ejbills** [comment]
macOS 12 will stop receiving updates this year I believe, is there really a point in supporting this version?

**Comment by illavoluntas** [comment]
It is also up to Shlomo, if he says it’s not a hard work. But if it’s not worth it, I agree this might not be necessary.

**Comment by ShlomoCode** [comment]
macOS 12.0 is missing `SCWindow` and `SCShareableContent`, but 12.3 will only require workarounds for some swiftUI modifiers (`bold`, `fontWeight`, `scrollDisabled`, `Color.clear.shadow`,), and `AnyShape`.

**Comment by ShlomoCode** [comment]
You can see what I've done so far at https://github.com/ShlomoCode/DockDoor/tree/macOS-12.3

**Comment by ejbills** [comment]
Closing this as stale, not planned. Will reopen if @ShlomoCode wants to continue with this effort
