### ISSUE TITLE
[BUG] Localized strings do not fit

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#284]
Screenshot 1: Cursor on the third string beginning from the bottom is too small. You have to resize the window to move it.
Screenshot 2: Some strings are too long and are not displayed entirely.

## Screenshots
![Capture d’écran 2024-08-31 à 13 19 31](https://github.com/user-attachments/assets/3024c6bd-1336-4c7d-b201-c1024a7d289f)
![Capture d’écran 2024-08-31 à 13 19 44](https://github.com/user-attachments/assets/1490faf0-9b0f-4231-a1ef-753e9e078ad1)

## Environment
 - macOS version: macOS 14.5
 - App version: 1.1.6

**Comment by illavoluntas** [comment]
Will this be addressed?

**Comment by ejbills** [comment]
@Kinark and I are working on redesigning the settings, if you've noticed (brand new intro screen, help settings tab, permissions redesign). This is on the todo list.

**Comment by illavoluntas** [comment]
Thank you!
