### ISSUE TITLE
[BUG] Modifier keys toggle previewed applications

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#285]
## Describe the bug
When hovering an application with opened windows, pressing any modifier key (Shift, Command, Control, Fn or Option) will automatically toggle the first window. This might interfere with app keyboard shortcuts.

## Steps to reproduce
- Hover over an application icon with opened windows.
- Press Shift, Command, Control, Fn or Option.

## Expected behavior
Modifier keys like that should not bring the window to front.

## Environment
 - macOS version: macOS 14.5
 - App version: 1.1.6

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
I noticed this a while ago, personally this is quite useful and is one of the cases where a bug can become a feature. I think for now, this will stay as I use it. Perhaps we should edit this issue to be geared towards documenting this as a use case, as right now it isn't documented anywhere.

**Comment by illavoluntas** [comment]
> I noticed this a while ago, personally this is quite useful and is one of the cases where a bug can become a feature. I think for now, this will stay as I use it. Perhaps we should edit this issue to be geared towards documenting this as a use case, as right now it isn't documented anywhere.

I agree this is useful, maybe document it?

**Comment by illavoluntas** [comment]
> I noticed this a while ago, personally this is quite useful and is one of the cases where a bug can become a feature. I think for now, this will stay as I use it. Perhaps we should edit this issue to be geared towards documenting this as a use case, as right now it isn't documented anywhere.

I agree this is useful. I might add this on README.md. Do we need a documentation?

**Comment by illavoluntas** [comment]
Thing that might not be practical is that it only toggles the first window.

**Comment by ejbills** [comment]
> Thing that might not be practical is that it only toggles the first window.

This is still useful imo

**Comment by illavoluntas** [comment]
Will be documented in #258.
