### ISSUE TITLE
[BUG] Windows have wrong size while they are not in the main screen

### ISSUE THREAD

**Issue by wjfu99** [ejbills/DockDoor#288]
## Describe the bug
When using multiple screens, the windows on the second or third screens will have the wrong size (the object of the preview window seems to have the right size, but the preview image it not).

## Steps to reproduce
- link multiple screens (for me, i use 3)
- preview app who has windows on other screens expect the main one
- the preview image of window on other screens have the wrong size

## Expected behavior
The preview image should have an appropriate size to align the object of the preview window

## Actual behavior
The preview image seems to be too small?

## Screenshots
The right windows are too small.
<img width="649" alt="image" src="https://github.com/user-attachments/assets/3a81ca30-ade0-43d0-bf9c-afabd521dbf1">
<img width="576" alt="image" src="https://github.com/user-attachments/assets/123e81f4-5f37-4114-a726-e41b50235df6">

## Environment
 - macOS version: 15.0
 - App version: 1.2.0

## Additional context

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Thanks for the report, I was able to patch this in v1.2.1.
