### ISSUE TITLE
[FR] Don't rearrange order of dock previews

### ISSUE THREAD

**Issue by tmnrdhf** [ejbills/DockDoor#292]
## Problem or Need
The whole time I was wondering why the dock previews did not really help me with window management. It was until I realized that everytime I clicked on a preview to open that window, the order of the previews rearranges. So every time I opened the previews I subconciously found myself searching for the preview I'm looking for, which subconsiously confused me all the time and is super annoying (although I love DockDoor for me personally this was the reason I had to deactivate it again).

## Proposed Solution
Can we have at least an option so that the previews never rearrange? That would be really amazing!

## Potential Impact
I'm sure that this is a common problem people have with DockDoor (but might not realize). Especially if they have used other dock preview apps or Microsoft Windows before (on Windows the previews never rearrange which is great). 

Thanks a lot in advance!

**Comment by ejbills** [comment]
This is because they are always sorted by the most recently used window. 

This is incredibly easy and will take me about 20 mins to add and release. I will do it once I have some time in a little bit. 👉😎👉

**Comment by ShlomoCode** [comment]
Actually, according to semvar, it's v1.3 :)

**Comment by tmnrdhf** [comment]
You are insane, thanks a lot! I will definitely buy you a coffee or two <3

However, I just tested the feature and for me it somehow does not work. I'm on the newest version and also tried to restart dockdoor after I changed the setting. But windows are still being rearranged every time I click on one.
