### ISSUE TITLE
[BUG] Preview is shown after mouse cursor is no longer hovering over app

### ISSUE THREAD

**Issue by zehDonut** [ejbills/DockDoor#295]
## Describe the bug
When the mouse is over an app icon but is moved away from the icon before the preview is shown (due to preview window open delay being set to a higher value), the preview still shows up after the delay.

## Steps to reproduce
- Set preview window open delay to a higher value, e.g. 1.5s
- Hover mouse over an app icon
- Remove mouse from app within delay time frame
- Preview is still shown
![dockdoor_preview_delay](https://github.com/user-attachments/assets/cb4cf43c-9f54-490f-a8d3-3d0193ec98b1)

## Expected behavior
The preview should not be shown if the mouse cursor is no longer hovering over an app.

## Actual behavior
A clear and concise description of what actually happened.

## Environment
 - macOS version: 15.0
 - App version: 1.2.3

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Closing as a duplicate issue

**Comment by zehDonut** [comment]
So there will be no way to change this behavior?

**Comment by ejbills** [comment]
> So there will be no way to change this behavior?

I just closed this as a duplicate bug report, as I opened the original report. I will fix this issue.
