### ISSUE TITLE
[BUG] Dock with sped up animations causes prematurely hidden window

### ISSUE THREAD

**Issue by gkrawiec** [ejbills/DockDoor#297]
## Describe the bug
with the update this past week, i can no longer hover over the preview windows. They do show up, but as soon as I try to move the mouse pointer into one of the previews in order to hover or select, the previews instantly close.
I already played around with the window buffer so that the window preview is next to or under the dock so that the pointer never but it still closes immediately.

## Steps to reproduce
- 

## Expected behavior
in the past I could move from the dock icon into the previews in order to select them. I would expect that to still work

## Actual behavior
the previews close immediately when the pointer leaves the dock icon. Even if it goes dierctly into the preview.

## Environment
 - macOS version: 14.6.1
 - App version: currently 1.2.3 but the problem showed up in thew previous version

## Additional context

- [ X] I have reviewed the open issues to ensure this is not a duplicate

**Comment by illavoluntas** [comment]
Duplicate of #291, version 1.2.3 specially patched the issue.

**Comment by illavoluntas** [comment]
Next time, please really review opened **and closed** issues. Issue titles are usually relevant and indicate the main problem.

**Comment by gkrawiec** [comment]
Sorry, but no. This is not about far previews. I saw that post and its video. 
This is ALL previews. I cant even reach a single preview. I already have 1.2.3 and the problem is still there.

**Comment by illavoluntas** [comment]
Well, before anything else, does the bug still show up in **1.2.3**? I’m unable to reproduce it.

**Comment by illavoluntas** [comment]
Oh, ok.

**Comment by illavoluntas** [comment]
> Sorry, but no. This is not about far previews. I saw that post and its video. This is ALL previews. I cant even reach a single preview. I already have 1.2.3 and the problem is still there.

You might want to try to reset DockDoor, but all your settings will be gone. `defaults delete com.ethanbills.DockDoor`

**Comment by illavoluntas** [comment]
> Sorry, but no. This is not about far previews. I saw that post and its video. This is ALL previews. I cant even reach a single preview. I already have 1.2.3 and the problem is still there.

Sorry for the misunderstanding

**Comment by illavoluntas** [comment]
@gkrawiec Have you also tried restarting DockDoor? As I am unable to reproduce the issue, it might help fixing it.

**Comment by gkrawiec** [comment]
Just tried 
- quitting 
- -resetting defaults
- opening app

problem is still there.

https://github.com/user-attachments/assets/2de66a22-49a9-40c8-95b6-5caa2186a4f3

**Comment by illavoluntas** [comment]
That is very strange, thank you for the precisions.
Do you happen to have multiple monitors?

**Comment by gkrawiec** [comment]
Nope, single internal laptop monitor. I did NOT have this problem in the release from before this week.
Though I did have the issue where dockdoor would stop working after a while (this has been fixed).

**Comment by illavoluntas** [comment]
If you have time and saved your work, you could also try restarting your Mac. But as restarting DockDoor didn't work, I'm not sure it might work...

**Comment by illavoluntas** [comment]
Could you please screenshot your General and Appearance settings too? Let's see if some settings are triggering this bug or not.

**Comment by gkrawiec** [comment]
Windows Switcher is DISABLED, all permissions are given.

<img width="651" alt="39345" src="https://github.com/user-attachments/assets/33740ba2-f730-446f-93d5-2672ec37220d">

<img width="637" alt="61178" src="https://github.com/user-attachments/assets/9c2e5d75-4e7b-4a1c-82a2-0260824d025e">

**Comment by illavoluntas** [comment]
What does changing `Preview Window Open Delay`'s value do? Is it the same?

> [!NOTE]
> I'm just trying ways to investigate why this is happening to you. I cannot reproduce the issue, even though I have approximately the same settings as you.

**Comment by gkrawiec** [comment]
No difference.

> What does changing `Preview Window Open Delay`'s value do (to a higher one)? Is it the same?
> 
> Note
> 
> I'm just trying ways to investigate why this is happening to you. I cannot reproduce the issue, even though I have approximately the same settings as you.

**Comment by illavoluntas** [comment]
Okay. Did you restart your Mac?
Another track you could follow is using `Pearcleaner` to completely uninstall DockDoor (delete all the files related to it), and reinstall from the GitHub repo.

**Comment by gkrawiec** [comment]
I've done the uninstall using pearcleaner. I should mention I install using brew cask.
I have NOT restarted the machine yet. I can't right now, I can try that monday morning.

**Comment by ejbills** [comment]
> Just tried 
> 
> - quitting 
> 
> - -resetting defaults
> 
> - opening app
> 
> 
> 
> problem is still there.
> 
> 
> 
> https://github.com/user-attachments/assets/2de66a22-49a9-40c8-95b6-5caa2186a4f3
> 
> 
> 
> 

Why does your dock instantly disappear?

**Comment by illavoluntas** [comment]
> > Just tried
> > 
> > * quitting
> > * -resetting defaults
> > * opening app
> > 
> > problem is still there.
> > 
> >   
> >     
> >     
> > 
> >     Screen.Recording.2024-09-07.at.10.19.41.AM.mov
> 
> Why does your dock instantly disappear?

Might be some trick using Terminal or simply animations are disabled (accessibility feature).

**Comment by illavoluntas** [comment]
@ejbills Are you able to reproduce this bug?

**Comment by gkrawiec** [comment]
I think it's from disabling the delay to open the dock. I use [tinkertool](https://www.bresink.com/osx/TinkerTool.html) to activate that.

<img width="810" alt="68997" src="https://github.com/user-attachments/assets/7517e1f9-3dd8-467c-8467-cb1e28e3f868">

> >     
> > 

> 
> Why does your dock instantly disappear?

**Comment by ejbills** [comment]
@gkrawiec it appears you ran this command to speed up the dock hiding animation:
defaults write com.apple.dock autohide-delay -float 0; defaults write com.apple.dock autohide-time-modifier -int 0;killall Dock

Can you please run this command to reset it to default, and see if the issue persists:
defaults delete com.apple.Dock autohide-delay; killall Dock

**Comment by ejbills** [comment]
i.e; 

please try to untick these 2 options:

Disable animation when hiding or showing Dock
Disable delay when showing hidden Dock

**Comment by gkrawiec** [comment]
i used Tinkertool to enable the animation option there (NOT the delay option I highlighted on my previous message)

ENABLING THE ANIMATION FIXES THE PROBLEM.

BUT.....i should mention, i've had the animation disabled since forever and it did not affect dockdoor. This problem started with last week's release.

thank you!

<img width="796" alt="91706" src="https://github.com/user-attachments/assets/aa196002-77a5-4cb3-bb4d-be26448514fd">

**Comment by ejbills** [comment]
> i used Tinkertool to enable the animation option there (NOT the delay option I highlighted on my previous message)
> 
> 
> 
> ENABLING THE ANIMATION FIXES THE PROBLEM.
> 
> 
> 
> BUT.....i should mention, i've had the animation disabled since forever and it did not affect dockdoor. This problem started with last week's release.
> 
> 
> 
> thank you!
> 
> 
> 
> <img width="796" alt="91706" src="https://github.com/user-attachments/assets/aa196002-77a5-4cb3-bb4d-be26448514fd">
> 
> 

I figured that was the issue, it's just something we didn't test for. I will see if I can make it compatible with this tinker tool option.

**Comment by illavoluntas** [comment]
If I remember correctly 1.2.0 changed the way DockDoor detected the Dock. This might be connected.

**Comment by gkrawiec** [comment]
> If I remember correctly 1.2.0 changed the way DockDoor detected the Dock. This might be connected.

Great catch. It didnt even cross my mind I have a non standard setting for the dock animation. It is something I just disable when I install macos.

thank you!

**Comment by illavoluntas** [comment]
> > If I remember correctly 1.2.0 changed the way DockDoor detected the Dock. This might be connected.
> 
> Great catch. It didnt even cross my mind I have a non standard setting for the dock animation. It is something I just disable when I install macos.
> 
> thank you!

You're welcome @gkrawiec! I was pleased to investigate the source of the problem :slightly_smiling_face:

**Comment by illavoluntas** [comment]
@ejbills I don't think TinkerTool is an open-source program. I hope you can figure out how it disables the Dock animation.

**Comment by gkrawiec** [comment]
maybe this?
https://www.xda-developers.com/how-accelerate-dock-macos-terminal/

> @ejbills TinkerTool isn't an open-source program. I hope you can figure out how it disables the Dock animation.

**Comment by illavoluntas** [comment]
Oh, yes, I even saw a video today on how to speed up this animation :man_facepalming:.

**Comment by ejbills** [comment]
> @ejbills TinkerTool isn't an open-source program. I hope you can figure out how it disables the Dock animation.

Anything that changes how the dock operates is simply editing the dock prefs file. This option in tinker tool is literally just running this command:

`defaults write com.apple.dock autohide-delay -float 0; defaults write com.apple.dock autohide-time-modifier -int 0;killall Dock`

**Comment by illavoluntas** [comment]
No problem then, let's hope there is a possible patch for DockDoor! :rocket:

**Comment by MattSuda** [comment]
I'm having the same issue with hovering over the window previews since the recent update.

I also have dock animations sped up using TinkerTool.

I'm really hoping that the recent changes can be updated to support these faster animations. The Dock is too slow without these options enabled, and I find the faster animations to be much better.

**Comment by MattSuda** [comment]
Not sure if it's related to this issue, but DockDoor just randomly stops running.

I restart DockDoor and I see it's running for a while and then suddenly it's not open and running anymore It just closes / crashes in the background. I haven't seen any other reports, so might be related to this issue here.

**Comment by illavoluntas** [comment]
> Not sure if it's related to this issue, but DockDoor just randomly stops running.
> 
> I restart DockDoor and I see it's running for a while and then suddenly it's not open and running anymore. It just closes / crashes in the background. I haven't seen any other reports, so might be related to this issue here.

#243 is similar, looks like that the bug reappeared…

**Comment by MattSuda** [comment]
With the previous bug, the preview windows would not show up, but the app would still be open. For this bug, when I check the menubar, the icon is also gone like the app has been closed out. Seems to happen after a few days of the app running.

Since I haven't seen any other reports, I thought it might be due to this other bug I am having because I have the sped up dock animations.

I'll keep an eye on the bug and next time I will check to see if the app process is still running or not.

**Comment by martinbaerwolff** [comment]
I had the same problem. I also set my dock to autohide and had no animation. I honestly can't remember if I had done this with a 3rd party app. But ChatGPT says that with the following bash command you can change the animation speed of the dock:
```bash
defaults write com.apple.dock autohide-time-modifier -float 0.001
killall dock
```

... and it works.

For me (Sequoia 15.0.1, DockDoor 1.2.9) the hovering over the preview window works if I set the animation speed > 0, even if I set it only marginally above 0. You won´t notice a difference to 0, it feels like there is no animation at all.

However, the preview window hovering does not work if I set the animation speed = 0.

Hope this helps :)

**Comment by MattSuda** [comment]
Thanks @martinbaerwolff that worked for me as well! Animation is still fast, I can't really tell a difference.

However, to me it seems that the dock hides too quickly sometimes now when trying to hover over the dock preview windows, so I would like to see #354 added as a feature.

Just note that now when you open up TinkerTool or another similar tool, it will show that "Disable animation when hiding or showing Dock" is no longer checked. But you can confirm that the command worked and is set up by opening /Users/YourUsername/Library/Preferences/com.apple.dock.plist in BBEdit and see that it now shows:

`<key>autohide-time-modifier</key>
<real>0.0010000000474974513</real>`

I'm still hoping this can be supported by default without having to do this workaround.

Also I never had that crashing issue that I mentioned earlier come back, so not sure what was causing that.
