### ISSUE TITLE
Ctrl+Tab: macOS location services shown in app preview display

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#3]
Intermittently, when pressing Ctrl+Tab, the first app preview shown is the macOS location services "arrow" icon (either the blue circle w/ white arrow, or just the basic black arrow).

**Comment by ejbills** [comment]
I will fix this in the next release, thanks for the report!

**Comment by ejbills** [comment]
Fixed, will be in 1.0.3.

**Comment by ejbills** [comment]
Is this specifically with brave browser too? 

Also, does it happen if you hover over that browser in your dock?

**Comment by ejbills** [comment]
Also, go into settings and pull that latest update. I just pushed it, let me know if issue persists.

**Comment by 0n0mat0p03ia** [comment]
> Is this specifically with brave browser too?

Yes.

> Also, does it happen if you hover over that browser in your dock?

No, the pop-up shows the correct window previews for all open windows in Brave.

**Comment by 0n0mat0p03ia** [comment]
> Also, go into settings and pull that latest update. I just pushed it, let me know if issue persists.

Installed the latest update. This was an intermittent issue so I'll report back if it happens again. 

Also, thx for the update to how the app icon and name are displayed when peeking, it's much easier to read now.

**Comment by 0n0mat0p03ia** [comment]
> Also, go into settings and pull that latest update. I just pushed it, let me know if issue persists.

Confirmed that the issue still exists with the latest update.
