### ISSUE TITLE
Scrcpy Window Not Shows

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#30]
When I hover over the [scrcpy](https://github.com/Genymobile/scrcpy/) icon in the Dock, DockDoor crashes. The error occurs even without `always-on-top` mode.
Seems to scrcpy windows have no `bundleIdentifier`:
![CleanShot 2024-06-26 at 17 27 33@2x](https://github.com/ejbills/DockDoor/assets/78599753/7a9fe4d0-f191-42a3-9ba8-d612b70a14b9)
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

**Comment by ShlomoCode** [comment]
Refs: https://github.com/lwouis/alt-tab-macos/pull/2624, https://github.com/Genymobile/scrcpy/issues/3684

**Comment by ejbills** [comment]
I will add safe-unwrapping to this variable as a quick fix. I will need to implement this scrcpy handler.

**Comment by ShlomoCode** [comment]
:+1: Now it doesn't crash but of course doesn't show a preview. Same with android studio emulator.

**Comment by skynet01** [comment]
I think Telegram app is also effected by this
