### ISSUE TITLE
⚠️ [ATTENTION] 1.2.4 doesn't launch ⚠️ Install 1.2.5 from the Releases section

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#302]
### v1.2.4 incorrectly resets the accessibility permissions and causes the application to crash instantly on launch. Please fix this issue by manually installing v1.2.5: https://github.com/ejbills/DockDoor/releases/tag/v1.2.5

If you did not upgrade to v1.2.4, please ignore this post.

**Comment by illavoluntas** [comment]
DockDoor fails to open, even a reset using Terminal cannot fix it.

**Comment by illavoluntas** [comment]
Users might get confused, I recommend preventing users from updating to 1.2.4.

**Comment by ShlomoCode** [comment]
Course for me too. Attached is a crash report, you can decode it using [MacSymbolicator](https://github.com/inket/MacSymbolicator)
[DockDoor-2024-09-08-220249.ips.zip](https://github.com/user-attachments/files/16923357/DockDoor-2024-09-08-220249.ips.zip)

**Comment by illavoluntas** [comment]
Well Shlomo it’s interesting to see your error report!

**Comment by ShlomoCode** [comment]
We don't need an crash report as this is reproduced even when run through Xcode:
```
DockDoor/DockObserver.swift:59: Fatal error: Can't get dock items list element
```
This means that for some reason the update has caused the accessibility permission to be reset, and `setupSelectedDockItemObserver` is called when the permission has not yet been granted, causing the crash.

**Comment by ShlomoCode** [comment]
As an interim solution, you can go into Privacy & Security, then Accessibility and Screen Recording, remove the existing item and re-add it from the Applications folder.

**Comment by jimmysmits** [comment]
> As an interim solution, you can go into Privacy & Security, then Accessibility and Screen Recording, remove the existing item and re-add it from the Applications folder.

Does not resolve the issue, still cannot launch the app after these steps

**Comment by ejbills** [comment]
v1.2.4 changed the build profile to another team I work for, which reset the permissions. **Please do not attempt to work around this issue.** Re-install v1.2.5 and it will be fixed.

**Comment by ejbills** [comment]
@illavoluntas I am going to hijack your initial post as I'm sure many people who downloaded 1.2.4 will be coming here for help.

**Comment by illavoluntas** [comment]
> @illavoluntas I am going to hijack your initial post as I'm sure many people who downloaded 1.2.4 will be coming here for help.

Thank you for fixing the problem in 1.2.5!
