### ISSUE TITLE
[FR] Add App Names to Window Switcher

### ISSUE THREAD

**Issue by mksoska** [ejbills/DockDoor#306]
## Problem or Need
Navigation between applications using the Window Switcher is pretty hard, when there are windows which cannot be easily distinguished by the preview image. Users can accidentally switch to wrong application.

## Proposed Solution
The Window Switcher should display App Name above the window preview image, same as in Dock Previews. 

## macOS Version
macOS 14.6.1 Sonoma

## App Version
v1.2.5

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by hasansultan92** [comment]
So the way I am understanding is that right above the window preview, show up the app icon and name?

How about the icon show up on the preview itself. For example if you have traffic light buttons on the right side, perhaps we show the the app icon on the left or bottom?

**Comment by mksoska** [comment]
I think we should be consistent with how the App Name is displayed in the Dock Preview – right above the window preview show the app icon and name.

**Comment by ejbills** [comment]
@mksoska discussion is moving to https://github.com/ejbills/DockDoor/issues/306

I posted a preview of a WIP of this feature, please let me know what you think
