### ISSUE TITLE
[BUG] DockDoor displays closed Notes and Calendar window as open

### ISSUE THREAD

**Issue by mksoska** [ejbills/DockDoor#307]
## Describe the bug
DockDoor shows Notes and Calendar window as open, even when the window has been closed. 

## Steps to reproduce
- Launch Notes/Calendar (opens a window)
- Close the window
- The DockDoor window preview of Notes/Calendar is still displayed (both in Dock Preview and Window Switcher), even though the window was closed.

## Expected behavior
No window preview of Notes/Calendar is displayed.

## Actual behavior
Window preview of Notes/Calendar is displayed.

## Environment
 - macOS 14.6.1 Sonoma
 - v1.2.5

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Looking into
