### ISSUE TITLE
Feature request: minimized and hidden window previews

### ISSUE THREAD

**Issue by langjacob518** [ejbills/DockDoor#31]
Minimized windows still showing up as "minimized window" instead of actually showing the preview. Using latest version of Sonoma on MBA M2. LOVE the app! If I could get this figured out this would be a staple in my toolkit.

**Comment by langjacob518** [comment]
Still having the same issue in 1.0.6 :/

**Comment by ejbills** [comment]
I have not figured out how to get previews of minimized windows. I will take a look at how to do this.

**Comment by skynet01** [comment]
This would be awesome, as most of the time my windows are minimized. What if you take a screenshot of the app  right when a minimize action happens?

**Comment by ShlomoCode** [comment]
> I have not figured out how to get previews of minimized windows. I will take a look at how to do this.

Alt-tab seems to uses ([1](https://github.com/lwouis/alt-tab-macos/blob/master/src/logic/Window.swift#L103-L108), [2](https://github.com/lwouis/alt-tab-macos/blob/master/src/logic/Window.swift#L103-L108)) the [`CGSHWCaptureWindowList`](https://github.com/lwouis/alt-tab-macos/blob/master/src/api-wrappers/PrivateApis.swift#L34-L42) private API to get screenshots of windows (and it works for minimized/full screen windows too)

p.s. It's your decision, but I would leave only the Dock peek functionality, which has no quality or open source alternative, and forgo a window switcher that already has a stable free open source software that has spent years optimizing and searching for the best and most efficient way, and has dozens of customization options (alt-tab)

**Comment by langjacob518** [comment]
Hey, just curious if you guys are still considering adding a feature to view minimized window previews or not? If not, I totally get it, just want to make sure since the issue was closed and I'm still only seeing the blank minimized view for minimized windows. Love the app, and appreciate you being so responsive and active. Kudos!

**Comment by ShlomoCode** [comment]
This issue is not closed, it's open. We just merged some duplicates

**Comment by langjacob518** [comment]
Oh my bad, I'm relatively new to Github. Thanks!

**Comment by Bentheminernz** [comment]
This app definitely needs this feature, its the only thing stopping me from switching over to it.

**Comment by langjacob518** [comment]
Same. It's FAR AND AWAY the best app in it's class and it's free. It's just this one thing that I really want to see in the next release.

**Comment by Write** [comment]
Such a great app indeed !
In the meantime, you guys can buy him a coffee. 😋
https://www.buymeacoffee.com/keplercafe

**Comment by skynet01** [comment]
bought him coffee ☕

**Comment by tayloreisele** [comment]
It was shared on Reddit that this has been implemented but I'm not seeing it with the most recent version. Can anyone verify? Thanks.

**Comment by langjacob518** [comment]
I'm on 1.1.4 and it's still the same for me.

**Comment by ShlomoCode** [comment]
It has been implemented but not yet merged into the code. It will probably be included in the next release

**Comment by langjacob518** [comment]
I've been anxiously awaiting! Can't wait to see it. You guys are seriously killing it with this app.

**Comment by ShlomoCode** [comment]
closes at https://github.com/ejbills/DockDoor/pull/234
@ejbills
