### ISSUE TITLE
[BUG] Setting "sort Window previews by date" does not work

### ISSUE THREAD

**Issue by tmnrdhf** [ejbills/DockDoor#312]
## Describe the bug
As mentioned [here](https://github.com/ejbills/DockDoor/issues/292#issuecomment-2333345356) already:

When you disable the option the preview windows are still being rearranged every time you click on one. It seems like the new setting just inverts the order so that the most recent window is now always shown in the most left spot instead of the most right spot. It does not disable the sorting what was the whole purpose of that setting.

## Steps to reproduce
- disable "sort Window previews by date"
- open multiple windows in an app
- click on windows in the preview of that app

## Expected behavior
When the option is disabled, the windows in the preview should never rearrange. (I believe on Microsoft Windows the order is simply based on the "creation" date of the window and therefore never changes.)

## Environment
 - macOS version: Sonoma 14.5
 - App version: 1.2.6

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Will look into

**Comment by tmnrdhf** [comment]
@ejbills thanks a lot! One last UX request on that: Could you invert the order of the windows? Currently, new windows are added on the left. However, this is very intuitive, since the common order is always left to right. That would be amazing.
