### ISSUE TITLE
Feature Request: Show full size previews of windows by hovering over it's mini view

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#32]
Like in [DockMate](https://www.macenhance.com/dockmate.html):

https://github.com/ejbills/DockDoor/assets/78599753/551f040d-b42b-4baa-a39f-f0881c94edfa

It's super useful, and is (in my opinion) the only game changer feature that DockDoor is missing.

**Comment by 0n0mat0p03ia** [comment]
I like this suggestion. Recommend this be a user-defined setting. Would need to play nicely with recommendation [#27](https://github.com/ejbills/DockDoor/issues/27) if that one is implemented too.

**Comment by skynet01** [comment]
plus one for this one

**Comment by ejbills** [comment]
I like this, I will try to add it in the coming days :)

**Comment by ejbills** [comment]
https://streamable.com/i0upts what do you guys think??

**Comment by ShlomoCode** [comment]
Looks good!
I suggest adding a border, and a Genie Effect animation like macOS (System Settings > Desktop & Dock > Minimize windows using)

**Comment by ejbills** [comment]
in v1.1.2

**Comment by 0n0mat0p03ia** [comment]
> Looks good! I suggest adding a border, and a Genie Effect animation like macOS (System Settings > Desktop & Dock > Minimize windows using)

As always, would like for any transition effect to be enabled/disabled in settings.

**Comment by ejbills** [comment]
> As always, would like for any transition effect to be enabled/disabled in settings.

Yes, there is no transition yet - it is instant. Will have to play around with that enhancement and it will be controlled with the toggle, for sure!

**Comment by 0n0mat0p03ia** [comment]
> in v1.1.2

With `Preview hover action->See a preview of the window enabled`, a squirqle (rounded circle) is displayed in the upper left corner of the screen when hovering over minimized and hidden window previews. Not sure what the expected behavior is.

**Comment by 0n0mat0p03ia** [comment]
Also: the preview image for `Preview hover action->See a preview of the window enabled` is a bit fuzzy/blurry. `Use Uniform Image Preview Radius` is enabled (I disabled it, didn't make a difference).

**Comment by ejbills** [comment]
> The preview image for `Preview hover action->See a preview of the window enabled` is a bit fuzzy/blurry. `Use Uniform Image Preview Radius` is enabled (I disabled it, didn't make a difference).
I fixed this, not sure what to do about the blurriness... I will look into it.

> 
> Also, lot's of great updates in this release, really appreciate the responsiveness to user feedback. Dock Door is really shaping up well now. Oh, and it looks like all transition effects can truly be turned off now, I'm not seeing any as I hover over dock icons. 👍👍👍

And that's great! You have posted a ton of great items that I wouldn't think of myself, and there has been tons of help from all of the contributos so development is moving quickly. It's a lot of fun!

**Comment by 0n0mat0p03ia** [comment]
v1.1.2

Looks like there's an issue when `See a preview of the window enabled` is set. 

Scenario is two adjacent apps in the dock:

- abc_app w/ one window, not minimized or hidden
- xyz_app w/ one window, minimized

Steps to reproduce:

1. Hover pointer over xyz_app dock icon (the minimized app)
2. Slide the pointer over to abc_app dock icon and hover

A preview hover for abc_app is shown even though the pointer remains on its dock icon. The preview hover remains on the screen as you slide back and forth over dock icons. It's dismissed if you move the pointer off the dock, or if you hover the pointer over another dock app that has an active, non-hidden, non-minimized window.

**Comment by ejbills** [comment]
Can you record what you mean and open an issue please?

**Comment by ejbills** [comment]
Maybe I fixed this with my other patch, can't seem to reproduce. My minimized window is accurately dismissed, along with the full preview for the non-minimized app.
