### ISSUE TITLE
[FR] Clicking on Window Switcher

### ISSUE THREAD

**Issue by iamEvanYT** [ejbills/DockDoor#323]
When you currently find the window you want in Window Switcher, you have to use the keybind to switch to it, even if it might be in mouse's reach.

Proposed Solution: Let you click on windows in Window Switcher, and focus that window.

**Comment by ejbills** [comment]
You can click on the window switcher

**Comment by iamEvanYT** [comment]
> You can click on the window switcher already

I just noticed, but it doesn't work half the time. Perhaps it is a bug?
