### ISSUE TITLE
[BUG] window with more than two tabs shows each tab as preview in dock

### ISSUE THREAD

**Issue by david-leeb** [ejbills/DockDoor#325]
When having multiple tabs open in, for instance, preview, each tab is treated as a separate window and shows up in the dock preview. For some reason this only happens if I have more than two tabs in one preview window. I have this problem with the option 'Ignore Apps with one window' activated.
It would be nice to have an option to disable that behavior, so multiple windows are shown as preview only when there is more than one window of the application open.

**Comment by ejbills** [comment]
This would be due to the application itself returning each tab as it's own macos window, in which DockDoor would have no method of filtering out those entries.
