### ISSUE TITLE
Dock peek: preview pop-up still displayed after app is quit from dock

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#33]
The dock peek preview pop-up can remain on the screen even after the target app is a closed from the dock. In the [attached video](https://github.com/ejbills/DockDoor/assets/166866908/0fb8099e-ea41-42f7-9770-266785ee242c), Firefox is quit, however the preview pop-up remains on screen. Presumably this is happening because the mouse pointer is hovering over the preview window, keeping it on screen until the preview is clicked or the pointer is moved away.

**Comment by ejbills** [comment]
This could be fixed by adding an observer listening for app quitting notifications, I will look into this.
