### ISSUE TITLE
[BUG]Issue with apps with multiple top level windows showing "ghost" previews after those windows have been closed

### ISSUE THREAD

**Issue by stevehoek** [ejbills/DockDoor#330]
## Describe the bug
I use Chrome with multiple profiles set up. When I open a Chrome top level window for Profile 1, 2, and 3 they all show up correctly in the DockDoor dock preview.  However, when I close one of the windows it still shows up in the dock preview and I have to use the traffic lights to close it (its not really open, I can't switch to it).  Even stranger, sometimes old previews come back when no windows are open for that app (eg all Chrome profile top level windows have been closed by Chrome is still running)

## Steps to reproduce
Configure Chrome with multiple profiles
Open all profiles as their own top level windows
Check the dock preview - it should be accurate
Close one or more of the top level windows
Check the dock preview - it should be accurate
Close all of the top level windows
Check the dock preview - it should be accurate

## Expected behavior
Show the actual windows that are open with current preview

## Actual behavior
"ghost" previews for windows that have been closed appear

## Environment
 - macOS version: macOS 15.0 Sequoia
 - App version: latest

## Additional context

- [x ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by smakhnist** [comment]
bug IMHO is a showstopper for using the application. I have IntellijIdea and am closing projects back and forth. and DockDoor never updates the list, and its list is entirely irrelevant, making the DockDoor's popup hint unusable.

**Comment by hasansultan92** [comment]
so lets say at time t0 you open multiple windows (3 google chrome windows), at time t1, you close one window (now there are two active google chrome windows). At time t1, when you hover the dock you see three windows still in the previews or at time t1+x you still see three google chrome windows?

Feel free to replace google chrome with another application, it is just an example here

**Comment by stevehoek** [comment]
I believe it’s more likely t1+x

I most often see it with MacUpdater, an app that runs in the menu bar and
daily runs a scan looking for software updates.  If it finds some it opens
its main window and I see two previews, one from when I closed the window
yesterday and one from today

**Comment by ejbills** [comment]
@stevehoek thanks for specifically mentioning macupdater. I was able to isolate the issue and am pushing the fix now.
