### ISSUE TITLE
[BUG] DockDoor does not show a preview Window if i have minimized the App i want to see. 

### ISSUE THREAD

**Issue by andyvan37** [ejbills/DockDoor#335]
## Steps to reproduce
- 

## Actual behavior
A clear and concise description of what actually happened.

## Environment
 - macOS version: [e.g. macOS 15.0 Sequoia]
 - App version: [e.g. 1.1.4]

## Additional context

- [ ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by StefanKiendl** [comment]
+1

As soon as a app window is minimized (e.g. with Cmd+M or yellow traffic light button 🚥) and residing in dock, it is not showed in DockDoor previews any more.

Other comparable apps have an option if minimized windows should be shown/covered in the preview, but I don‘t see anything comparable in DockDoor settings.

Having all, really all, windows of an running app covered is IMHO a killer/must function for DockDoor, as it makes the user independent of context knowledge and former actions to find all his windows.

**Comment by au-ganymede** [comment]
+1

**Comment by Timoms** [comment]
+1 
Don't really see the need for previews when minimised windows are not shown.
It is handy for some overlapping windows but in general I see what I have open anyways.

**Comment by illavoluntas** [comment]
@andyvan37 @StefanKiendl @au-ganymede @Timoms
Did you try to first hover the app's icon **before** minimizing it? That might be a temporary solution to your problem...

**Comment by Timoms** [comment]
> @andyvan37 @StefanKiendl @au-ganymede @Timoms Did you try to first hover the app's icon **before** minimizing it? That might be a temporary solution to your problem...

Thats indeed a funny workaround - but not the way I want to use my Mac :D 
Take your time to work on the problem, its still a really promising dock preview app compared to the other apps available.

**Comment by illavoluntas** [comment]
> > @andyvan37 @StefanKiendl @au-ganymede @Timoms Did you try to first hover the app's icon **before** minimizing it? That might be a temporary solution to your problem...
> 
> Thats indeed a funny workaround - but not the way I want to use my Mac :D Take your time to work on the problem, its still a really promising dock preview app compared to the other apps available.

Yes, you would better ask @ejbills (project owner) or @ShlomoCode, as I unfortunately don't have Swift knowledge.

**Comment by ejbills** [comment]
> > @andyvan37 @StefanKiendl @au-ganymede @Timoms Did you try to first hover the app's icon **before** minimizing it? That might be a temporary solution to your problem...
> 
> Thats indeed a funny workaround - but not the way I want to use my Mac :D Take your time to work on the problem, its still a really promising dock preview app compared to the other apps available.

Due to macOS window management limitations, DockDoor can only capture previews of minimized windows if they were previously displayed while DockDoor was running. Since DockDoor is designed to run from system startup to shutdown, this isn't an issue during normal operation. However, if you launch DockDoor after using other applications, it won't be able to show previews of already-minimized windows. We don't plan to implement additional workarounds for this technical constraint. Thank you for bringing this to our attention!

**Comment by lePereT** [comment]
Hi @ejbills just to say that with latest DockDoor, if I open the app, then open 2 windows of Chrome (from completely closed) and minimise one of them, then that minimised window is not shown. This doesn't match with the behaviour you described above, it also doesn't align with the behaviour in Windows or HyperDock (the best Mac implementation of dock previews to date - which DD will soon overtake!). Also wanted to say it's fantastic to see the progress that DockDoor is making.

**Comment by ejbills** [comment]
> Hi @ejbills just to say that with latest DockDoor, if I open the app, then open 2 windows of Chrome (from completely closed) and minimise one of them, then that minimised window is not shown. This doesn't match with the behaviour you described above, it also doesn't align with the behaviour in Windows or HyperDock (the best Mac implementation of dock previews to date - which DD will soon overtake!). Also wanted to say it's fantastic to see the progress that DockDoor is making.
> 
> 
> 
> EDIT - if I hover over Chrome's dock icon before minimising then DD retains a preview

I am able to reproduce, I can easily add in window registration when a window is created. Would you mind opening an issue on github?

**Comment by lePereT** [comment]
done!
