### ISSUE TITLE
[FR] Support custom screen size for hover display

### ISSUE THREAD

**Issue by maranmaran** [ejbills/DockDoor#337]
## Problem or Need
Really no need for "What is this" "Extra extra small" and such

## Proposed Solution
Just scaler slider or perhaps a % input

**Comment by apotenza92** [comment]
I think another good approach may be to size the preview as a % of the screen size. I often change from external monitors to laptop display and the sizes don't adjust to suit the display size. Could just be 5% 10% 15% etc. as the preview size.

**Comment by maranmaran** [comment]
> I think another good approach may be to size the preview as a % of the screen size. I often change from external monitors to laptop display and the sizes don't adjust to suit the display size. Could just be 5% 10% 15% etc. as the preview size.

Yes, I meant to write "slider" and wrote dropdown. However, I think I'd just prefer a % input 0-100 and that's it...

**Comment by apotenza92** [comment]
@ejbills inspo was the way Raycast lets you set up custom window layouts using % width or % height as an input 😄

**Comment by maranmaran** [comment]
> A slider based on screen size is so simple, and works way better than the method I ended up going with. Can't believe I didn't think of this initially, haha! Just noting here that I plan on switching to a percentage based system in a coming patch.

thanks
