### ISSUE TITLE
[FR] Consistent design & settings for previews in dock AND window switcher

### ISSUE THREAD

**Issue by tmnrdhf** [ejbills/DockDoor#341]
## Problem or Need
For some reason the dock previews have way more options in terms of design and settings (e.g. behavior) like for example app icon and interaction elements (e.g. radio buttons). 

## Proposed Solution
A lot of for the dock preview also make sense for the window switcher preview so I don't really understand why there is such a big difference. Therefore it would be great if those two could be made more consistent.

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by ejbills** [comment]
What kind of customization options are you hoping to see in the window switcher settings?

**Comment by ejbills** [comment]
Completed in https://github.com/ejbills/DockDoor/commit/b0a1d342adcdaba7e4f2b4bbe3df7f69be78557d

Refer to https://www.threads.net/@kepler.cafe/post/DELZiFIz1gP?xmt=AQGzOwJT0bYUvmR9pTicXfZu4Q12mOhf-slr_2uspwvQxA
