### ISSUE TITLE
[EN] Open new window with Shift + LMB

### ISSUE THREAD

**Issue by Galder7** [ejbills/DockDoor#345]
## Problem or Need
What problem are you trying to solve? What need do you have that isn't currently met?

I can't stand MacOS default launching new window of app. There is Cmd+N or RMB -> Open new window, but this option is discouragingly high on action list. I always want to open window by just clicking on app in dock, because to use CMD + N I need to firstly go to this app and then it moves me to other space or makes different weird behavior. I just need super fast intuitive option for opening new window from dock by clicking maybe Shift + LMB. I tried this and I assume it does nothing. CMD + LMB opens application folder.

## Proposed Solution
How do you think this problem could be solved or this need could be met?

## Alternative Solutions
Have you thought of any other ways to address this? If so, what are they?

## Potential Impact
How would this feature benefit the project and its users?

## macOS Version
What version of macOS are you using? (e.g., macOS 15.0 Sequoia)

## App Version
What version of our app are you currently using? (e.g., 1.1.4)

- [ ] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by ejbills** [comment]
Closing as not possible, I researched and was unable to find a way to universally open a new window for an application programatically.
