### ISSUE TITLE
[BUG] When dock is hidden, can't click on the window overlays

### ISSUE THREAD

**Issue by riadhrebei** [ejbills/DockDoor#348]
## Describe the bug
When the Dock is hidden, hovering over windows to select a pane causes the Dock and its windows to hide again unexpectedly.

## Steps to reproduce
1. Ensure the Dock in DockDoor app is set to hidden mode.
2. Move the cursor to the area where the Dock or windows should appear.
3. Hover over the windows to select a specific pane.
4. Observe that the Dock and its windows hide before a selection can be made.

## Expected behavior
The Dock and its windows should remain visible when the cursor is hovering over them to allow the user to select a pane.

## Actual behavior
The Dock and its windows hide prematurely, preventing the user from selecting a pane.

## Screenshots
![CleanShot 2024-10-22 at 14 26 21](https://github.com/user-attachments/assets/63ac0422-d2aa-4992-8be5-970e628304eb)

## Environment
- macOS version: macOS 15.0.1 Sequoia
- App version: *e.g.* 1.2.9

## Additional context
This issue significantly impacts usability when using the app in hidden Dock mode. 

- [ ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by illavoluntas** [comment]
@riadhrebei Did you tried lowering the window buffer? That might actually help.

**Comment by ejbills** [comment]
Are you by any chance using a sped-up dock animation?
