### ISSUE TITLE
[FR] Solid Preview Background Colour

### ISSUE THREAD

**Issue by LukeAndrewColeman** [ejbills/DockDoor#352]
## Problem or Need

Hey, great app. Would it be possible to add an option to have a solid background colour for the window preview background instead of just having the blurred background.

## Proposed Solution

You could add an option in the app settings to add a solid background colour.

## Potential Impact

I believe this would be a pretty cool feature to have, this would give the user the option to match their current style/colour scheme and make the app more fun and personalised.

## macOS Version

Sequoia 15.0.1

## App Version

1.2.9

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by Q3Defender** [comment]
Fully support this - it would also make the previews in the windows switcher preview more prominent

**Comment by ejbills** [comment]
This was added in a prev verison
