### ISSUE TITLE
[BUG] open pop-ups should not be captured.

### ISSUE THREAD

**Issue by mietl** [ejbills/DockDoor#355]
## Describe the bug
1.   It should not capture pop-ups.
2.  Even after the pop-up is closed, it still remains present.

## Steps to reproduce
After the pop-up in the application is closed, use the DockDoor preview feature.

## Expected behavior
I think the pop-up should be ignored.

## Actual behavior
The pop-up can be previewed, and it still remains visible after being closed.

## Screenshots
<img width="1677" alt="image" src="https://github.com/user-attachments/assets/066588a4-b33c-4748-8294-55b0f2d04f07">
<img width="1739" alt="image" src="https://github.com/user-attachments/assets/87d74478-89a0-486d-a80a-fa7ec4ea6fdb">

## Environment
 - macOS version:  macOS 15.0.1 Sequoia
 - App version: 1.2.9

## Additional context

- [ x ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by martinn000** [comment]
I don't think popups should be removed but they should definitely be smaller than they currently are

**Comment by mietl** [comment]
> I don't think popups should be removed but they should definitely be smaller than they currently are

A pop-up window usually stays on top of the main window, and switching to the main window means displaying the pop-up.

**Comment by mietl** [comment]
The main issue is that the pop-up is closed, but I believe it shouldn’t remain.

**Comment by marcelharinck** [comment]
> The main issue is that the pop-up is closed, but I believe it shouldn’t remain.

Totally agree!

**Comment by marcelharinck** [comment]
I'm having the same issues with Outlook:

![image](https://github.com/user-attachments/assets/ae8c602b-6b5c-4b25-a4d2-838d01e28571)

**Comment by hasansultan92** [comment]
Hmm so in the above cases, once the pop up window is closed/exited out of the window still shows up in the window switcher and the dock previews?

**Comment by mietl** [comment]
> Hmm so in the above cases, once the pop up window is closed/exited out of the window still shows up in the window switcher and the dock previews?

Yes, that’s correct! Even after the pop-up window is closed or exited, it still appears in the window switcher and dock previews.

**Comment by marcelharinck** [comment]
> Hmm so in the above cases, once the pop up window is closed/exited out of the window still shows up in the window switcher and the dock previews?

Indeed :(

**Comment by ejbills** [comment]
Hi everyone, please update to v1.3 and let me know if this issue persists. It should be fixed, and popups should be removed now. If not, please tag me here and I will investigate further. Thanks!

@mietl @marcelharinck @martinn000

**Comment by ejbills** [comment]
@mietl thank you for reporting this issue, and apologies for not getting around to this issue till now. This issue will be fixed in the upcoming v1.4. I have confirmed that the bug no longer exists in the Passwords app and Settings app respectively, which allowed me to reliably create the issue. Please watch out for the update in the coming days.

**Comment by mietlove** [comment]
> thank you for reporting this issue, and apologies for not getting around to this issue till now. This issue will be fixed in the upcoming v1.4. I have confirmed that the bug no longer exists in the Passwords app and Settings app respectively, which allowed me to reliably create the issue. Please watch out for the update in the coming days.

Thank you for your time and effort to fix the iussue. 
I hope it will get better.

**Comment by mietl** [comment]
> @mietl thank you for reporting this issue, and apologies for not getting around to this issue till now. This issue will be fixed in the upcoming v1.4. I have confirmed that the bug no longer exists in the Passwords app and Settings app respectively, which allowed me to reliably create the issue. Please watch out for the update in the coming days.

Thank you for your time and effort to fix the iussue.
hope it gets better.
