### ISSUE TITLE
UI elements as windows in Logos Bible Software

### ISSUE THREAD

**Issue by daroga** [ejbills/DockDoor#36]
Before I share my issue, I just want to thank you for the work on this app. I've been using it for the last few days and love it. It's fast and less clunky than other options out there. I really, really appreciate your work. Thank you so much!

The issue I'm having is with Logos Bible Software's UI rendering and how DockDoor is picking up on that. It's possible this is just an issue with Logos Bible Software, but perhaps other programs use a similar window rendering scheme that cause similar issue.

In Logos, when pulling up a search box for searching within a book, a small search box pops up in the right hand corner of the book. This screen shot shows it in the context of the menu bar: 

<img width="288" alt="Screenshot 2024-06-28 at 10 07 58 AM" src="https://github.com/ejbills/DockDoor/assets/39595374/2c0f7123-a5be-430a-8109-90ecc48926a3">

However, in Dockdoor, this little search box becomes its own full-fledged window (and is also gigantic on screen compared to the other windows--the below-screen shot only shows about half of the thumbnail).

<img width="1680" alt="Screenshot 2024-06-28 at 10 03 50 AM" src="https://github.com/ejbills/DockDoor/assets/39595374/53f77d2f-572f-48eb-8662-53c919c07784">

Also, closing the search box in Logos doesn't seem to "unload" that window in DockDoor. The only way to make it go away in DockDoor is to close Logos entirely.

If I can help at all in figuring this out, please let me know. Happy to do whatever I can!

**Comment by ejbills** [comment]
Hmm, definitely shouldn't be happening. I will reach out to you once I have some time to look into this.

**Comment by marjue12255** [comment]
Hello
Same effect with Citrix Viewer App and Garmin's Base Camp.

![IMG_2534](https://github.com/ejbills/DockDoor/assets/96430436/7aca7439-08de-4bcb-8525-d09f4e14b96b)

**Comment by ShlomoCode** [comment]
Also happens for Google Chrome's translation popup
![CleanShot 2024-07-14 at 04 12 37@2x](https://github.com/user-attachments/assets/5fee4fcb-8220-4ebf-9406-42d90b6d6ae5)

**Comment by ShlomoCode** [comment]
Maybe we can filter by window size? However, see https://github.com/lwouis/alt-tab-macos/issues/1466
