### ISSUE TITLE
[BUG] window switching command + tab is invalid

### ISSUE THREAD

**Issue by YuZhengshun** [ejbills/DockDoor#360]
## Describe the bug
thanks for you app !
my system version is 14.5 but as title descriped  window switch can not by comman  +tab

## Screenshots

<img width="631" alt="image" src="https://github.com/user-attachments/assets/269a8daa-6d4f-4875-8cea-76f1ac2dc14c">
<img width="641" alt="image" src="https://github.com/user-attachments/assets/6752f289-f735-488a-92cc-f907121cbdd3">

**Comment by hasansultan92** [comment]
Hey, thanks for using. Are you a new user?

Does not allow you to change it?

**Comment by YuZhengshun** [comment]
> Hey, thanks for using. Are you a new user?
> 
> Does not allow you to change it?

yes i'm new  UI allow me to change it but not useful   when i changed tab it changed back
