### ISSUE TITLE
[BUG] not possible to open adjacent windows with hiding docker 

### ISSUE THREAD

**Issue by turik97** [ejbills/DockDoor#364]
when there are multiple windows and you want to open the left/right one you have to move the coursor to the main window first (vertically to top) so the dockbar does not get hidden, i suggest adding some delay before hiding the previews so if i hover over them they don't disappear 

https://github.com/user-attachments/assets/01382e4d-a08e-47f6-aaef-b00fc10ec68d

**Comment by illavoluntas** [comment]
Are you using any tools to speed up the dock hiding animation?

**Comment by turik97** [comment]
is it my problem or it's still not fixed?

**Comment by ejbills** [comment]
The dock hiding causes the app that gets quickly passed over to register 2 separate "hover" actions. The first one gets successfully ignored, however the second one either: triggers the window to be dismissed, or causes the app that was quickly passed over to incorrectly present itself. v1.3 does not address this issue, but I am working on this and have been testing different approaches.

**Comment by ejbills** [comment]
I have identified and implemented a fix for this in development. Going to do some more testing, but it solves the issue mentioned here. Please stay tuned for 1.3.1, and hopefully all mouse movement related issues will be resolved.

**Comment by turik97** [comment]
https://github.com/user-attachments/assets/91549f0a-df41-4089-b618-473fe8d4ebcb

the issue still persists, here is the demonstration

**Comment by ejbills** [comment]
Which version? This is fixed on my machine.

**Comment by turik97** [comment]
> Which version? This is fixed on my machine.

Sorry did not update. Fixed as of 1.3.2

**Comment by turik97** [comment]
Now when I switch apps it moves the bottom part of the window to the height of the dock (resizing i guess) but it's wrong in my case cause I have hiding dock. Plz fix

**Comment by ejbills** [comment]
Turn off "keep dock open with previews"
