### ISSUE TITLE
[FR] Allow Reduced App Preview

### ISSUE THREAD

**Issue by j01am** [ejbills/DockDoor#367]
## Problem or Need
What problem are you trying to solve? What need do you have that isn't currently met?

The app only shows "opened" app previews, but not the one opened and reduced.

## Proposed Solution
How do you think this problem could be solved or this need could be met?

It could be great to add this ability in the settings

## Alternative Solutions
Have you thought of any other ways to address this? If so, what are they?

no

## macOS Version
What version of macOS are you using? (e.g., macOS 15.0 Sequoia)

macOS 15.1

## App Version
What version of our app are you currently using? (e.g., 1.1.4)

1.2.9

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

PS : Thanks a lot for your nice app ! :D

**Comment by ejbills** [comment]
Minimized and hidden app previews are included in the app, so long as DockDoor is running in the background to keep track of your windows. Hope this helps!
