### ISSUE TITLE
Feature Request: See Preview of Minimized Windows

### ISSUE THREAD

**Issue by langjacob518** [ejbills/DockDoor#37]
This app is the best of its kind of all that I've used EXCEPT that I can't see my minimized windows in the dock (which really seems like the main draw to me). If you could add a settings pane that allows you to show minimized windows in full preview as well, that would be absolutely excellent. 

A settings menu in general would be very useful and a few other features that would be great in the settings menu are 
-toggle if the menu bar icon shows up in the menu bar 
-ability to disable ctrl+tab functionality 
-a plus button at the end of the preview to open a new instance/window of the application

Again, love the app and want to see it succeed! Thanks for the release

**Comment by rochakagrawal** [comment]
Excellent points. Yes, even I noticed that some apps show the window while others don't. Would appreciate the setting to be standard for all.

**Comment by ejbills** [comment]
Consolidating in: https://github.com/ejbills/DockDoor/issues/31
