### ISSUE TITLE
[BUG] the window just won't always open

### ISSUE THREAD

**Issue by turik97** [ejbills/DockDoor#371]
## Describe the bug
quite often when i press on the window in the multiple windows app it just won't open 

## Steps to reproduce
not sure yet how exactly it happens

## Screenshots
https://github.com/user-attachments/assets/eb0c1033-4d20-4842-9112-54f0906bcffc

## Environment
 - macOS version: Seqouia 15.1
 - App version: 1.2.9

**Comment by ejbills** [comment]
It can fail if the DockDoor settings pane remains open, this is a bug with the accessibility API. If you notice some weird behavior, closing the settings window should resolve the issue 9 out of 10 times. If not, please tag me to reopen this issue. I will be adding some messaging to warn users of this issue, so it's not a shot in the dark. Thanks for reporting!
