### ISSUE TITLE
[FR] add an option of not hiding the windows preview when click on the app

### ISSUE THREAD

**Issue by turik97** [ejbills/DockDoor#372]
I think it would be great if there is an option 'Don't hide previews when clicking on the App' because oftentimes I'm clicking on the hidden app to maximize it and take a look for a few secs what's there, and then bring the mouse to the top left corner and hide it again. By adding this option, when I click on the app, looking at its content for whatever I needed, I could easily hide it again just from the preview above the icon. So quick.

**Comment by ejbills** [comment]
working on it

**Comment by turik97** [comment]
@ejbills the functionality is there but now the bug emerged - when you hide the app from the preview it opens full preview after the click.

**Comment by ejbills** [comment]
> @ejbills the functionality is there but now the bug emerged - when you hide the app from the preview it opens full preview after the click.

What do you mean hide the app from the preview? Please attach a recording showing your issue
