### ISSUE TITLE
[FR]Make selection in the windows switcher more prominent

### ISSUE THREAD

**Issue by Q3Defender** [ejbills/DockDoor#373]
## Problem or Need
What problem are you trying to solve? What need do you have that isn't currently met?
When using the windows switcher it is hard to see the selected one. 

## Proposed Solution
How do you think this problem could be solved or this need could be met?
Maybe adding a frame overlay of the selected window. I assume you use the gradient coloring from the dock previews where this is fine but for the windows switcher it could be better ;-)

## Alternative Solutions
Have you thought of any other ways to address this? If so, what are they?

## Additional context
I love your app!

## Potential Impact
How would this feature benefit the project and its users?
Even more usability!

## macOS Version
What version of macOS are you using? (e.g., macOS 15.0 Sequoia)
15.2 Beta 
## App Version
What version of our app are you currently using? (e.g., 1.1.4)
1.2.9

- [ X] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by ejbills** [comment]
For the window preview hover action, select “see a large preview of the window.” Then, look at the colored border that highlights the image, as you mentioned. Is that what you were referring to you want to be added to the window switcher preview?

**Comment by ejbills** [comment]
Combining with https://github.com/ejbills/DockDoor/issues/340

Addressing this issue in 1.3.1

**Comment by Q3Defender** [comment]
no, it is more to have the selected or hovered application in the Window switcher highlighted. You can see in the dock the window is already not so clear to see but this is not a problem, since you anyway use the mouse to select




￼




but in the Window switcher it is hard to see the selection and there you just use Alt+Tab but not the mouse

￼

In the Alt Tab Tool there is the background solid and so better to see where you are.

￼



I like the gradient selection for the high lighting but maybe a sold background would be an alternative option!


Best, Andreas


On 25. Nov 2024, at 18:49, ejbills ***@***.***> wrote:



For the window preview hover action, select “see a large preview of the window.” Then, look at the colored border that highlights the image, as you mentioned. Is that what you were referring to you want to be added to the window switcher preview?

**Comment by ejbills** [comment]
@Q3Defender check out https://github.com/ejbills/DockDoor/issues/260#issuecomment-2498962317
