### ISSUE TITLE
[FR] Allow option to not display hidden or minimized windows in window switcher

### ISSUE THREAD

**Issue by SarcevicAntonio** [ejbills/DockDoor#375]
## Problem or Need
I like to leave windows open but minimize them to use later. I don't want them showing up in my window switcher.

## Proposed Solution
I'd like an option to not show hidden or minimized windows inside the window switcher. They are already greyed out, so I hope just hiding them shouldn't be too hard.

## Alternative Solutions
I can close windows I don't use right now, but sometimes that is impractical, for example if I have a browser window with a bunch of tabs open I want to keep for later.

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by ejbills** [comment]
Your feature request will be about 3 lines of code 🤣

I will add it in the next version

**Comment by SarcevicAntonio** [comment]
Awesome, glad to hear! Thanks 🙏🏼😊

**Comment by ejbills** [comment]
To confirm, only the window switcher right? If you hover open an app icon, you want to see the minimized windows there?
