### ISSUE TITLE
DockDoor only showing one window preview

### ISSUE THREAD

**Issue by SRFurst** [ejbills/DockDoor#378]
I found DockDoor when searching for DockMate. I must be doing something wrong, however, because when I hover over an icon in the dock it only shows me a single window preview and not previews of all open windows for that application. The app is FIrefox and the OS is 15.1.1.

Thanks!

**Comment by illavoluntas** [comment]
Put all Firefox windows in the front and hover again the dock, that might solve your issue. 
That’s because DockDoor is made for running from startup to shutdown, so if you start it when macOS is running, you might not see all windows until you put them individually on the front.

**Comment by SRFurst** [comment]
Two issues:

Turns out I am looking to see Tabs in Firefox, not Windows. The Window previews do, in fact, work but DockMate also shows the tabs while DockDoor does not.
I have DockDoor set to open at login in Settings. I can see it in my Login Items. However, it does not seem to load on reboot/first login. If I then log out and log back in it gets started. Thoughts? (I can send screenshots if desired)

Without the ability to see previews of Tabs I do not find DockDoor to be useful.

Thank you!


From: ejbills ***@***.***>
Reply-To: ejbills/DockDoor ***@***.***>
Date: Monday, November 25, 2024 at 10:47 AM
To: ejbills/DockDoor ***@***.***>
Cc: Sheldon Furst ***@***.***>, Author ***@***.***>
Subject: Re: [ejbills/DockDoor] DockDoor only showing one window preview (Issue #378)


Please see @illavoluntas<https://urldefense.com/v3/__https:/github.com/illavoluntas__;!!Mih3wA!H4D2jnr6hkgTpcCwrcURLW_E12cvrV0TCD_DhrB_Pc7zDe3FQ9mqfNCxjK-MoxXvMUWJtEqd5FeSTOAZionE9to$> comment for context.

DockDoor uses a different method of discovering windows than apps like DockMate. Windows that are interacted with across spaces, while DockDoor is active and running in the background, will show up in the preview. Hope this helps!
