### ISSUE TITLE
Preview dont work fine

### ISSUE THREAD

**Issue by Csomm004** [ejbills/DockDoor#379]
## Describe the bug
I must open youre app and then i must all Windows open complete first before youre app can show the previews
see that in video
https://github.com/user-attachments/assets/e65c0260-2686-4b11-a9c2-059ce908020d

## Steps to reproduce
- 

## Expected behavior
-

## Actual behavior
-

## Screenshots
-

## Environment
 - macOS version: macOS 15.1.1 Sequoia
 - App version: 1.4

## Additional context

- [x ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Please refer to https://github.com/ejbills/DockDoor/issues/378#issuecomment-2496914418
