### ISSUE TITLE
Feature Request: Show window-name, choose window-frame-color

### ISSUE THREAD

**Issue by brunbjoern** [ejbills/DockDoor#38]
It would be very helpful to identify a window if you could display the window name, e.g. the folder name or the document name.

I would find it also helpful if you could define the window frame's color.

Many thanks for DockDoor!

**Comment by ShlomoCode** [comment]
> It would be very helpful to identify a window if you could display the window name, e.g. the folder name or the document name.

https://github.com/ejbills/DockDoor/issues/20

**Comment by ejbills** [comment]
Added, more customization with color theming is planned.

**Comment by 0n0mat0p03ia** [comment]
In regards to this latest enhancement:

- It would be nice for this to be a user-defined setting (i.e., show or don't show the window name), **and/or**
- The current placement of the scrolling window name partially obscures content in the preview window itself. Considering placing the window title right after the app name, above the preview window. In this way,  no content in the preview would be obscured. **and/or**
- In line with our discussions about animations, allow the scrolling effect to be turned off, either as a separate user-defined setting, or turned off via a global 'disable animations' setting

**Comment by 0n0mat0p03ia** [comment]
Also: another option for displaying the window name is to show a tooltip when hovering over the preview. For those that want a cleaner interface, this perhaps could be a user-defined setting in lieu of showing a scrolling window name.

In terms of features and UI/UX, I appreciate that it's not easy to satisfy everyone. Not every feature or UI element can be user-defined, however, supporting user-defined configuration when possible allows each person to tailor the UI/UX closer to their liking.
