### ISSUE TITLE
[BUG]DockDoor crashes after restart

### ISSUE THREAD

**Issue by SRFurst** [ejbills/DockDoor#380]
Mac Mini M4
Mac OS 15.1.1

DockDoor is set to run as a login item. After a restart, on first log in, DockDoor does not appear in the menu bar. Partial Crashlog below.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               DockDoor [476]
Path:                  /Applications/DockDoor.app/Contents/MacOS/DockDoor
Identifier:            com.ethanbills.DockDoor
Version:               1.3 (1.3)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-11-25 20:36:49.5833 -0700
OS Version:            macOS 15.1.1 (24B2091)
Report Version:        12
Anonymous UUID:        2D785789-20E5-6803-EDAF-FE2A2ADB6E6F

Time Awake Since Boot: 29 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001a016aa08

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [476]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x1a016aa08 _assertionFailure(_:_:file:line:flags:) + 268
1   DockDoor                      	       0x1027f1100 0x1027c8000 + 168192
2   DockDoor                      	       0x1027f0adc 0x1027c8000 + 166620
3   libdispatch.dylib             	       0x18f318658 _dispatch_client_callout + 20
4   libdispatch.dylib             	       0x18f319ea0 _dispatch_once_callout + 32
5   DockDoor                      	       0x1027f9fec 0x1027c8000 + 204780
6   DockDoor                      	       0x1027fa0c0 0x1027c8000 + 204992
7   CoreFoundation                	       0x18f5a6800 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
8   CoreFoundation                	       0x18f63766c ___CFXRegistrationPost_block_invoke + 88
9   CoreFoundation                	       0x18f6375b4 _CFXRegistrationPost + 436
10  CoreFoundation                	       0x18f57543c _CFXNotificationPost + 732
11  Foundation                    	       0x19071db14 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
12  AppKit                        	       0x1930e4598 -[NSApplication _postDidFinishNotification] + 284
13  AppKit                        	       0x1930e4348 -[NSApplication _sendFinishLaunchingNotification] + 172
14  AppKit                        	       0x1930e27a8 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 500
15  AppKit                        	       0x1930e23b0 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 488
16  Foundation                    	       0x19074679c -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 316
17  Foundation                    	       0x190746594 _NSAppleEventManagerGenericHandler + 80
18  AE                            	       0x196a95134 0x196a89000 + 49460
19  AE                            	       0x196a94a58 0x196a89000 + 47704
20  AE                            	       0x196a8dfa4 aeProcessAppleEvent + 488
21  HIToolbox                     	       0x19a93fc4c AEProcessAppleEvent + 68
22  AppKit                        	       0x1930dbc84 _DPSNextEvent + 1420
23  AppKit                        	       0x193a1bddc -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
24  AppKit                        	       0x1930cea64 -[NSApplication run] + 480
25  AppKit                        	       0x1930a52e8 NSApplicationMain + 888
26  DockDoor                      	       0x1027cabd0 0x1027c8000 + 11216
27  dyld                          	       0x18f148274 start + 2840

Thread 1:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x18f4c60e8 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x80000001028cfbf0   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000600000e30300
    x4: 0x0000000000000000   x5: 0x000000016d635dd0   x6: 0x0000000000000074   x7: 0x0000000000000000
    x8: 0x0000000000000155   x9: 0x000000008b2a1813  x10: 0x0000000000000154  x11: 0x00000000000002d0
   x12: 0x00000000000007fb  x13: 0x00000000000007fd  x14: 0x000000008b4a2010  x15: 0x000000008b2a1813
   x16: 0x000000008b400000  x17: 0x0000000000000010  x18: 0x0000000000000000  x19: 0x00000001028d2268
   x20: 0x80000001028cfbf0  x21: 0x0000000000000000  x22: 0x000000000000000b  x23: 0x000000000000001b
   x24: 0x0000000000000046  x25: 0x00000001028cf090  x26: 0xd000000000000021  x27: 0x0000000000000000
   x28: 0x000000016d636238   fp: 0x000000016d635fb0   lr: 0x00000001a016aa08
    sp: 0x000000016d635ee0   pc: 0x00000001a016aa08 cpsr: 0x60000000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x1027c8000 -        0x10290bfff com.ethanbills.DockDoor (1.3) <1d74ab47-2263-36b3-b7a7-ebdaadff298f> /Applications/DockDoor.app/Contents/MacOS/DockDoor
       0x102a5c000 -        0x102a9ffff org.sparkle-project.Sparkle (2.6.4) <0e273e3e-459c-3fa6-9a86-4754c5cc30ff> /Applications/DockDoor.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x10d3bc000 -        0x10d3c7fff libobjc-trampolines.dylib (*) <f1242604-dcb7-30a9-a19a-182991e6e645> /usr/lib/libobjc-trampolines.dylib
       0x110770000 -        0x110ed3fff com.apple.AGXMetalG16G-B0 (322.10) <ffa8f3da-c294-327e-8614-1f36026c0730> /System/Library/Extensions/AGXMetalG16G_B0.bundle/Contents/MacOS/AGXMetalG16G_B0
       0x1a0132000 -        0x1a06d8fff libswiftCore.dylib (*) <b8658c99-e96f-3c81-8ddf-a1af18150ee4> /usr/lib/swift/libswiftCore.dylib
       0x18f314000 -        0x18f35afff libdispatch.dylib (*) <567f0d28-5eeb-3713-89bb-c221d61a30cd> /usr/lib/system/libdispatch.dylib
       0x18f534000 -        0x18fa28fff com.apple.CoreFoundation (6.9) <ae4610f8-7c5c-3484-858e-cae7457d206e> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x190714000 -        0x191553fff com.apple.Foundation (6.9) <132e6011-7617-32ea-9624-0860d3ab14e0> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1930a1000 -        0x19449cfff com.apple.AppKit (6.9) <f6d80158-7279-340b-81e7-94e875967778> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x196a89000 -        0x196afdff7 com.apple.AE (944) <c859086e-8eb3-3969-8e2b-3a748120dab7> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
       0x19a916000 -        0x19ac1dfff com.apple.HIToolbox (2.1.1) <7129a8bf-ce8b-39c6-8565-b280af625fac> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x18f142000 -        0x18f1c47b7 dyld (*) <5ca59b26-65ac-3e9a-89bd-3ffd45a097c2> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18f4c4000 -        0x18f4d0fff libsystem_pthread.dylib (*) <97366a98-0b27-364f-bf0e-395bf521343f> /usr/lib/system/libsystem_pthread.dylib

**Comment by ejbills** [comment]
Only with the launch at login option enabled?

**Comment by SRFurst** [comment]
Correct. First login after reboot. Subsequent logins after reboot are fine.

Weird.

From: ejbills ***@***.***>
Reply-To: ejbills/DockDoor ***@***.***>
Date: Tuesday, November 26, 2024 at 10:54 AM
To: ejbills/DockDoor ***@***.***>
Cc: Sheldon Furst ***@***.***>, Author ***@***.***>
Subject: Re: [ejbills/DockDoor] [BUG]DockDoor crashes after restart (Issue #380)


Only with the launch at login option enabled?

**Comment by SRFurst** [comment]
For no good reason I am no longer experiencing crashes on restart and DockDoor is loading normally. I have about 6 crash logs from earlier but I can no longer reproduce the problem.

Sorry to have troubled you.

Sent from my iPhone

On Nov 26, 2024, at 10:54 AM, ejbills ***@***.***> wrote:

﻿

Only with the launch at login option enabled?
