### ISSUE TITLE
[FR] move highlighted window in window switcher or dock view to another display/screen

### ISSUE THREAD

**Issue by georgesnow** [ejbills/DockDoor#390]
## Problem or Need
window is on a different screen than expected or need to have it moved to the active screen you are working.

## Proposed Solution
keyboard shortcut and menu option to move the highlighted window to  the next and/or specific display/screen and/or  the active screen that has the mouse

## Alternative Solutions
i could use bettertouchtool or fastscript maybe with some applescript, but presents some diffculties with assign a keyboard shortcut specific to just preview window

## Potential Impact
this should be off by default and triggered only by menu option or keyboard script

## macOS Version
macOS 15.0 Sequoia

## App Version
1.3.2

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request
I did not see similar feature request

**Comment by musca999** [comment]
In hyperdock, as I'm sure you're aware, when you moused over the dock icon and previews of the open windows popped up, you could swipe up on the window you wanted and it would be "pulled" into the current Desktop. Very convenient feature. I think that is the FR being requested here and maybe I didn't quite understand the wording.

**Comment by ejbills** [comment]
working on it, this feature heavily uses private, undocumented Apple APIs from 2022. Will try and get something like this working.
