### ISSUE TITLE
[FR] Option to force window switcher list all windows using multiple rows

### ISSUE THREAD

**Issue by i0ntempest** [ejbills/DockDoor#395]
## Problem or Need
Currently when there are 4+ windows, some windows gets pushed off screen and one has to hit tab multiple times to see them.

## Proposed Solution
Add an option to have window switcher list all windows at once, using more than one rows of windows if needed, and scale them as needed. Basically what's in Windows or AltTab app.

## Alternative Solutions
N/A

## Additional context
![image](https://github.com/user-attachments/assets/08865dfa-9db5-4f0e-8572-f508e5549bce)

## Potential Impact
The point of the window switcher imho is to have all windows in view upon hitting alt+tab.

## macOS Version
15.1

## App Version
1.3.2

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by ejbills** [comment]
Duplicate.
