### ISSUE TITLE
[BUG] Preview stops working after Screen share in MS Teams

### ISSUE THREAD

**Issue by thisisjagan** [ejbills/DockDoor#397]
## Describe the bug
After Dockdoor is opened, it works without any issues. However, once Screensharing is performed in MS Teams, it stops showing preview.

## Steps to reproduce
Open Dockdoor and let the preview show as usual. Set up a call in MS Teams and screenshare. 

## Expected behavior
Preview should continue to work

## Actual behavior
Preview stops works

## Environment
 - macOS version: macOS 15.0 Sequoia
 - App version: Latest

## Additional context

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
I am able to reproduce this, and it is a very odd issue... I don't know why another app starting a screen share would affect DockDoor at all. I will diagnose this further and try to get a patch out soon.

**Comment by ejbills** [comment]
It's an issue with ScreenCaptureKit, migrating off of it in the next version
