### ISSUE TITLE
Dock peeking: app name and icon extends beyond the window preview border

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#4]
When peeking a dock app: the name of the app and it's icon both extend slightly above the gray border of the pop-up preview window. Depending on the content of the app under the pop-up window, the app name in the pop-up window can be difficult to read clearly (it looks especially bad if the app under the pop-up window has text, which clashes with the app name in the pop-up window, creating a jumbled mess of text). Recommend extending the pop-up window's opaque border slightly more so that it entirely encompasses the app's name, or find another solution to prevent this issue from occurring.

**Comment by ejbills** [comment]
I will play around with a strong shadow behind the text

**Comment by ejbills** [comment]
Labels will have a strong drop shadow in 1.0.3
