### ISSUE TITLE
[BUG] DockDoor silently quits occasionally

### ISSUE THREAD

**Issue by stevehoek** [ejbills/DockDoor#409]
## Describe the bug
DockDoor silently quits occasionally.  I first notice no dock previews, then check the menu bar and the icon is gone, and then check Activity Monitor and the process is not running.  There is no notice of this, like a crash report or anything.  I can restart it manually and all works fine again.  I would say this has been happening more since macOS 15.2.  I use my MBP constantly and would say it happens every few days... its hard to say.

## Steps to reproduce
None

## Expected behavior
Don't quit without notice

## Actual behavior
Occasionally quits without notice

## Screenshots
None

## Environment
 - macOS 15.2
 - latest

## Additional context
None

- [x ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Do you ever watch DMCA protected content, like Netflix, on your computer? There is a bug in the screencapture API which causes a fatal error in DockDoor. I can reliably make DockDoor quit by having a Udemy course open in Safari and hovering over it.

**Comment by stevehoek** [comment]
Occasionally Netflix but the last two time this has happened it wasn’t open.

**Comment by ejbills** [comment]
If you have a show open on Netflix and you hover does it cause the silent crash?

**Comment by stevehoek** [comment]
Yes, that does cause DockDoor to silently quit in a similar way to what I'm seeing.  But what I'm seeing Netflix or anything similar is not open.  

Why does it quit the whole app instead of just failing to get the screenshot?

**Comment by ejbills** [comment]
Consolidating this issue into #399
