### ISSUE TITLE
[BUG]After minimizing the window, the preview cannot be displayed in real-time.

### ISSUE THREAD

**Issue by ryanwuson** [ejbills/DockDoor#412]
## Describe the bug
After minimizing the window, the preview cannot be displayed in real-time.

## Steps to reproduce
Situation One:
1. Open the first Finder window, and there will be a preview on the Dock.
2. Press Cmd + N to open a second Finder window, and then press Cmd + M to minimize it. When the mouse is moved to the Finder icon, there will be only one preview, and the minimized window will not display a preview.

Situation Two:
1. Open two Finder windows, move the mouse to the Finder icon, and two previews will appear.
2. Switch the directory in one of the windows, press Cmd + M to minimize it, and when the mouse is moved to the Finder icon, the window that has switched the directory will not display the corresponding preview.

## Expected behavior
Preview real-time updates

## Actual behavior
Preview is not updated in real time

## Screenshots
Situation One
https://github.com/user-attachments/assets/e6f1cd13-0935-46ed-b8a3-bd1437bac6a4

Situation Two

https://github.com/user-attachments/assets/46331c5f-90fe-4aab-95f2-405c442d678d

## Environment
 - macOS version:  macOS 15.1.1 Sequoia
 - App version:  1.1.4

## Additional context
No

- [ ✓ ] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
This will be addressed in the next version!
