### ISSUE TITLE
Dock peek & Ctrl+Tab: closed modal window still displayed in app window preview 

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#48]
Testing 1.0.11.

Dock peek and Ctrl+Tab are displaying a preview for an app modal window that is no longer open. Specifically, the preview is showing the modal window for the Bitwarden add-on in Brave (Chrome), which was opened previously but is now closed. Closing the modal window in the app preview (via "X") removes it and it is no longer displayed thereafter.

**Comment by ejbills** [comment]
Chromium browsers love spawning windows it seems. Any windows its showing DO currently exist, so that isnt incorrect, however there may be a "isHidden" flag or something similar I can use to filter out those stragglers.

**Comment by ejbills** [comment]
Is this present in the latest version?

**Comment by 0n0mat0p03ia** [comment]
Unable to reproduce the issue testing with the Bitwarden plug-in, I think you can close this for now.

I did produce something similar when Brave displays the following modal:
![Screenshot 2024-07-11 at 10 13 13 PM](https://github.com/user-attachments/assets/a35c437f-0944-42e3-8e7f-eaa68611b5df)

A preview for the modal is displayed in the dock pop-up preview and Ctrl+Tab switcher, all blown up and fuzzy. I think this is the expected behavior, actually. I don't think this is worth investigating since a modal like this would be dismissed by the user within seconds and rarely appear in DockDoor.

**Comment by ejbills** [comment]
Fair enough!
