### ISSUE TITLE
Enhancement suggestion: user-defined delay for peek pop-up window display

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#5]
Considering allowing users to define the time interval before the peek pop-up window is displayed when hovering the  mouse cursor over a dock icon. Currently, the pop-up window displays very quickly, which is distracting if the user is simply moving the cursor across the dock, and wasn't intending to generate the peek pop-up window.

**Comment by ejbills** [comment]
This is a very simple addition, I will add it in the next release.

**Comment by ejbills** [comment]
Will be in 1.0.3
