### ISSUE TITLE
Request: add new quit functionality to README 

### ISSUE THREAD

**Issue by ejbills** [ejbills/DockDoor#56]
@ShlomoCode you recently added the force quit button, can you please document this functionality in the README? You can mention this issue in your PR.

**Comment by ShlomoCode** [comment]
Something like that?

**Help**
- I click on the purple quit button in the preview and the app doesn't close
- - You can hold the Option (⌥) key while clicking to force quit.

**Comment by ejbills** [comment]
Yes, also in the main function section. It's not immediately obvious that purple = shut down the app, in my opinion.
