### ISSUE TITLE
Enhancement: App Window Interaction

### ISSUE THREAD

**Issue by stevenlis** [ejbills/DockDoor#57]
Thank you so much for sharing your work with the community. 

I'd like to suggest an improvement to the app's interaction. DockDoor is the kind of app that doesn't need an app window since it just integrates a functionality into the system. The only window it has or needs is a Settings/Preferences window. Many developers like to create a menu icon.

I found an app with an interesting design called [Clop](https://lowtechguys.com/clop/).
![CS-EVshz5sZ@2x](https://github.com/ejbills/DockDoor/assets/33796896/b00732cc-60c8-4fdb-8fea-8d78d687949c)

If the app is not running, launch it, and it will start with the settings window displayed.  You can close the settings window. If you launch the app again, the settings window will reappear, allowing you to adjust settings as needed. To quit the app, simply click the "Quit" button. I find it tedious and unnecessary to go to the menu bar, find the icon, click open settings, and then adjust.

Btw I'm currently experiencing a bug where the menu icon fails to appear with "Show Menu Bar Icon" when I launch the app.

I'm on macOS 14.5 (23F79) with ??? (There appears to be no "About" section in the settings window to display the app version.)

**Comment by ejbills** [comment]
I like this, I just am apprehensive as I assumed users wouldn't want it to run silently in the background. This assumption seems to be incorrect, so I will make this the default functionality if the Show Menu Bar Icon toggle is off. Thanks for your suggestion!
