### ISSUE TITLE
The user cannot know which version he is using

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#59]
> There appears to be no "About" section in the settings window to display the app version.

Originally reported by @stevenlis at https://github.com/ejbills/DockDoor/issues/57

**Comment by stevenlis** [comment]
I've found a workaround: simply click "update".

![CS-GuDDWCHo@2x](https://github.com/ejbills/DockDoor/assets/33796896/d6ce7e22-6477-4fa3-a0ee-7171f7a218d6)

**Comment by ejbills** [comment]
The update page will be more informative in the next update:
<img width="598" alt="Screenshot 2024-07-03 at 9 19 47 PM" src="https://github.com/ejbills/DockDoor/assets/74191134/11768abf-c65d-49eb-bbb8-7dddb9b8d1d7">

**Comment by ShlomoCode** [comment]
@ejbills What do you think about this?
![CleanShot 2024-07-04 at 14 23 12@2x](https://github.com/ejbills/DockDoor/assets/78599753/49a29535-ad0f-4d2f-8308-7de266321c8b)
