### ISSUE TITLE
Dock Peek: Window titles too small in some circumstances

### ISSUE THREAD

**Issue by lint2015** [ejbills/DockDoor#61]
When Window Size is set to a smaller option, if you have some taller windows, due to the minimum padding between the traffic lights and the window title, the title often becomes so small that it barely fits a single character.

A suggestion to resolve this is to move the window title to the base of the window preview screenshot rather than the top right.

Thanks for the great work!

<img width="362" alt="Screenshot 2024-07-04 at 10 28 23 AM" src="https://github.com/ejbills/DockDoor/assets/39164595/55368818-3667-4099-bdbf-0d43a53f8385">

**Comment by ejbills** [comment]
Hey, I like your suggestion. Admittedly, I didn't test on super small windows, I apologize. Window titles will be readable in the next version :)
