### ISSUE TITLE
BUG: When window switcher is enabled, holding option to force quit an app auto-hides the window

### ISSUE THREAD

**Issue by ejbills** [ejbills/DockDoor#63]
@ShlomoCode did you notice this as well?

**Comment by ShlomoCode** [comment]
No, I'm not using the window switcher. I'll check it out!

**Comment by ShlomoCode** [comment]
I was unable to reproduce the issue: https://share.cleanshot.com/KMGrG620Kh3JWsBPy5DW
Both soft quit and hard quit work for me. Could it be that you didn't press the button accurately?
There is a general problem with our traffic light buttons, which are only pressed in their center. This is what I tried to fix in #53 but still haven't been significantly successful

**Comment by ejbills** [comment]
I think you're right, sorry for the false alarm!
