### ISSUE TITLE
Interested in new app icon? Similar to existing one?

### ISSUE THREAD

**Issue by VisualisationExpo** [ejbills/DockDoor#65]
Hi,

I was wondering what the thoughts are on an app icon made in Sketch using vector tools? Similar to the existing icon?

I have been working on one in Sketch that perhaps you can use? I'll make sure it fits properly on macOS icon grid too if you decide to wanting this icon.

It was quite fun to make.

I've added a preview
![AppIcon@2x](https://github.com/ejbills/DockDoor/assets/86615159/0a642fd2-2667-4429-a209-5683e92cc4c5)

**Comment by ShlomoCode** [comment]
The project owner is @ejbills but I like it, it's more realistic and clean

**Comment by ejbills** [comment]
@VisualisationExpo This looks amazing! Yes please, lets move forward with this. What do you need from me?

**Comment by VisualisationExpo** [comment]
> @VisualisationExpo This looks amazing! Yes please, lets move forward with this. What do you need from me? My one request is less obvious reflections in the windows as they are quite prevalent, but otherwise I love it!

Thank you.. all good point too. I just need know if the colors are OK and if you think the windows' edges should be less blurred - in favor of a hard edge? I'll touch up the windows glare too and make them less obvious / intrusive.

Is the blue color OK and is the flower pot's placement fine? need a windowsill for the potted plant if made smaller?

I'm glad you like the icon so far.

**Comment by ShlomoCode** [comment]
I think the flower pot should be a little higher, flower pots are on the windowsill, not hanging below it

**Comment by ejbills** [comment]
> > @VisualisationExpo This looks amazing! Yes please, lets move forward with this. What do you need from me? My one request is less obvious reflections in the windows as they are quite prevalent, but otherwise I love it!
> 
> Thank you.. all good point too. I just need know if the colors are OK and if you think the windows' edges should be less blurred - in favor of a hard edge? I'll touch up the windows glare too and make them less obvious / intrusive.
> 
> Is the blue color OK and is the flower pot's placement fine? need a windowsill for the potted plant if made smaller?
> 
> I'm glad you like the icon so far.

Do what you think looks best:)

**Comment by VisualisationExpo** [comment]
I updated the icons - the flower ones is a bit goofy. numbers 5 and 6 are without windowsill or flowerpot. number 6 has the eyes, mouth and window content moved down a little. 

The individual icons is at 1024 in this image. For smaller sizes, like 128px and below there's gonna be removal of a few things.

![Screenshot 2024-07-05 at 00 58 01](https://github.com/ejbills/DockDoor/assets/86615159/daed11dc-b400-441a-a6e2-1e01fea3abf4)

**Comment by ejbills** [comment]
I like the 4th the best!

**Comment by Write** [comment]
Cute Icon. I love the 6th one. (But I love them all)

**Comment by hasansultan92** [comment]
I love these @VisualisationExpo!

**Comment by VisualisationExpo** [comment]
I've updated the icon yet again.. felt the need to work on the plant and windowsill and more. 

I consider this final..  Should I fork the project and make a pull request or just post the full .icns here in the issue?

_I believe I just uploaded my Aural icon directly when I suggested an icon for the developer on that project._ 

![DockDoor_AppIcon](https://github.com/ejbills/DockDoor/assets/86615159/5eb305a4-48c4-41ee-b618-60745663c81e)

**Comment by VisualisationExpo** [comment]
icns version of above
https://drive.google.com/open?id=1i-9pJFcAQ0kngrv8-hOr-HMMAgn9kQ7d

**Comment by ShlomoCode** [comment]
@VisualisationExpo If it's not difficult for you, I'd be happy if you could also send the version without the shelf (6)
Thanks!

**Comment by VisualisationExpo** [comment]
@ShlomoCode here
https://drive.google.com/open?id=15nSvn7eAAYdIIpNBSt1lGpxpCHZh5XV8

**Comment by VisualisationExpo** [comment]
Anything needed. Just ask. Tweaks here and there within my capability.
Perhaps a night time window look and/or a darkened icon.

**Comment by ejbills** [comment]
This will be in v1.1.1! Thanks a ton @VisualisationExpo!

**Comment by VisualisationExpo** [comment]
> Maybe we'll also update the menu bar icon?

What would that look like? Some windows half opened? Or a little cute face?

**Comment by VisualisationExpo** [comment]
> This will be in v1.1.1! Thanks a ton @VisualisationExpo!

You're welcome and thank you for accepting my icon. And If a better icon comes along I won't feel bad if you decide to swap out the icon in favor of the new one.. remember that I have yet to create the 128x128 pixel icon to use in the Dock. For now it looks OK, but I feel like it could be sharper when in the Dock.
