### ISSUE TITLE
Ctrl+Tab and Dock peek: clicking "X" does not close app's window

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#7]
In both Ctrl+Tab and dock peek, clicking the "X" in the upper right corner of the window preview doesn't do anything. What is the expected behavior when clicking "X"?

**Comment by ejbills** [comment]
The way this works is by grabbing the close button ui element (with the accessibility api) like so:
`AXUIElementCopyAttributeValue(windowRef, kAXCloseButtonAttribute as CFString, &closeButton)`

Some windows do not have this attribute, leading to it failing to close. I will look into making the X only show up on a window preview if that close button attribute exists.

**Comment by ejbills** [comment]
I published some changes to this functionality in 1.0.4. Mind reviewing and reporting back?

**Comment by 0n0mat0p03ia** [comment]
Just tested Brave, Firefox, and Finder using 1.0.5 and it works. Thx for the fix!

One small note: depending on the content in an app's window, the "X" in the preview pop-up can sometimes be very difficult to see. For example, in Brave the default background color for a new private window is dark purple. The  "X" blends into it almost completely. Not sure there's much you can do about that. Just an FYI in any case.
