### ISSUE TITLE
Feature Request: Bringing minimized applications to the front just as hidden apps

### ISSUE THREAD

**Issue by UnknownCrafts** [ejbills/DockDoor#73]
I just got the new update and the hidden apps functionality is working perfectly. I just wanted to know if minimized apps could also be forced to come up to the front just like hidden apps, right now when a minimized app is opened from another space(not desktop) then the app would just open on the desktop but it doesn't get focused(like I am not forced out of my current space). I am not too sure if this was intended that's why I have put this as a feature request.

**Comment by ejbills** [comment]
Hi yes I will add this, this is an oversight on my part :P

**Comment by UnknownCrafts** [comment]
DockDoor V1.1.0, has this feature now, thank you! 

I will be closing the issue now.
