### ISSUE TITLE
Bug: Clicking dock peek preview sometime fails to bring that window to front

### ISSUE THREAD

**Issue by upstroke-version** [ejbills/DockDoor#74]
Clicking dock peek preview sometime fails to bring that window to front, it just loses focus of the current window and don't bring up the clicked window.
Somehow, double clicking preview makes it work perfectly without failing.

**Comment by ejbills** [comment]
Weird, does that happen on a specific app? Can't get it to fail on my end. 

Also which macos version are you on?

**Comment by upstroke-version** [comment]
I think Safari fails most frequently. I'm using latest macOS Sequoia beta, but I've encountered similar window switching issue on previous versions of macOS when creating some automation with Shortcuts app, so I don't think macOS version is the issue.
I'll try to reproduce the bug in safe mode, it might be just an interference with my other 3rd party apps.

**Comment by upstroke-version** [comment]
Tested on safe mode, it still happens.
I'm not sure if this bug is widespread or not, but maybe could you add a workaround for those who experiences this bug?
When I previously experienced similar issues making a shortcut, a simple harmless workaround, which was just calling window forwarding action two times in a row, worked and fixed the issue. Maybe you could add similar workaround to DockDoor...? Just a proposal.

**Comment by ejbills** [comment]
Can you record a short clip of this? I could add in a failsafe check to re-attempt the forwarding action on a given window. It's weird that it defocuses the current window though, so something *is* triggering.. weird.

**Comment by upstroke-version** [comment]
https://github.com/ejbills/DockDoor/assets/96179742/f955a28a-222a-41fa-92ba-9844bb0f908d

**Comment by romanmorozov81** [comment]
The same bug, Microsoft Excel. Sonoma 14.5.

**Comment by ejbills** [comment]
The source of this problem is if you have the DockDoor settings page open. It seems macos gets confused when we attempt to bring a window to the front, when our own app has its settings open.

Closing the settings window makes the issue go away. If anyone still has issues with this, even with the settings page closed, ping me and I will reopen this issue.

**Comment by rupak0577** [comment]
@ejbills Issue still exists even with settings closed. Oddly for me, it works correctly only when the settings page is open. And there's another issue where the preview fails to load for the same app after failing to bring the window to the front unless you hover over some other app in the dock.

**Comment by romanmorozov81** [comment]
Yes issue is still exist. Opened or closed settings doesn't help. I have to open preview and click on it two times, before it'll work. Like in video posted here earlier. Tried different settings, updated to last version nothing helps. App is mostly unusable because of this annoying but.

**Comment by anatolii-yemets** [comment]
Same here. @ejbills consider reopening this.
