### ISSUE TITLE
Feature Request: Show menu bar icon when app icon is clicked

### ISSUE THREAD

**Issue by DavidKarelin** [ejbills/DockDoor#76]
Currently, if you opt to hide the menu bar icon, you can only get it back by quitting and re-launching the app. Since you can’t access the menu bar icon when it’s hidden, the only way to quit the app that I can see is to find it in Activity Launcher and quit it. Another app I have installed that’s meant to run in the background has this handled more gracefully, where you can opt to hide the menu bar icon, but even if the app is opened, opening the app reveals the menu bar for a few seconds in the menu bar. Basically I just want the menu bar icon to be revealed when clicking on the app icon if possible. Thanks!

**Comment by Promises** [comment]
Alternatively just open settings if the app is launched while it's already running.

**Comment by DavidKarelin** [comment]
> Alternatively just open settings if the app is launched while it's already running.

How can I do this? I can only see how to open the seetings window from the menu bar icon.

**Comment by ShlomoCode** [comment]
> Another app I have installed that’s meant to run in the background has this handled more gracefully, where you can opt to hide the menu bar icon, but even if the app is opened, opening the app reveals the menu bar for a few seconds in the menu bar.

Yes this should be DockDoor's behavior. It seems to be a bug

**Comment by ShlomoCode** [comment]
The problem seems to be that `applicationDidFinishLaunching` is not called if the aoo is already open. I'll move the initialization to `applicationDidBecomeActive`.

**Comment by ejbills** [comment]
REOPENING: We will need to find another method of achieving this. `applicationDidBecomeActive` seems to invoke often, and not only when the app icon is clicked.

**Comment by ShlomoCode** [comment]
I found a solution in this MIT app: https://github.com/sindresorhus/System-Color-Picker
Preparing PR...
