### ISSUE TITLE
BUG: When hovering over dock icon, screen flashes white for a split second

### ISSUE THREAD

**Issue by DavidKarelin** [ejbills/DockDoor#78]
I have a monitor set up alongside my iMac, watching content on my iMac while doing work on the monitor. Sometimes when I hover over a dock icon on the monitor, the iMac screen will flash white for a split second. Really distracting and annoying.

**Comment by ejbills** [comment]
So this is a monitor plugged directly in to your mac? or via displaylink?

Definitely shouldn't be happening. I'm testing right now on multiple monitors.

**Comment by DavidKarelin** [comment]
Yes, directly plugged in using USB-C to HDMI. I’ve gone ahead and attached a video of the problem. It’s low quality and grainy to make it uploadable, but the gist of it is that my cursor moves from the calendar icon to the notes icon, and the iMac screen flahses white as soon as it happens. On my end, I’ve noticed that this seems to only happen with icons that the app is going to display something for. For icons where the app is closed or I don’t a window of the app open, nothing happens. Only when the app is going to display some window does the flash happen. Also, there seems to some cooldown time. This happens for any app icon that’s going to display something, but once I hover over the app icon and it displays whatever it’s going to display, if I hover over that app icon again, it displays without issue. This cooldown period is suspiciously close to 60 seconds, the Window Cache Lifespan. My guess? This is some unintended animation generated when creating the images shown when hovering. I’ve also narrowed down this issue to DockDoor by confirming that this issue doesn’t happen when DockDoor is not open. That’s all the information I’ve got for you. 

https://github.com/ejbills/DockDoor/assets/155956154/40e5bd14-d879-4b36-a546-04f7534f78a3

**Comment by hasansultan92** [comment]
Interesting issue, I wonder if this has something to do with one of the gradient libraries @ejbills. I am also using a second monitor with a Mac but the monitor is connected straight from the HDMI port on the Mac to the HDMI port on the monitor (no adapters), I do not have the same issues as @DavidKarelin

**Comment by DavidKarelin** [comment]
I think I’ve narrowed down the cause of the issue to Netflix. This flash is the behavior of Netflix when you take a screenshot, which DockDoor does every time it goes to display something. So the issue still persits (mometary flash when DockDoor displays something), but only with Netflix. DockDoor doesn’t do this flash in any other context (well I haven’t tested all the other streaming services, I’d imagine a few of them also have this safeguard as well).

**Comment by ejbills** [comment]
Closing this as this is simply an anti-piracy measure in place with the Netflix app. Thanks @DavidKarelin!
