### ISSUE TITLE
Enhancement suggestion (dock peek): clicking a dock icon should close the pop-up window preview

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#8]
Currently, when dock peeking, the pop-up preview of an app's window(s) remains on screen even after the user clicks the app's dock icon. Since the user is explicitly summoning the app to the foreground by clicking its dock icon, consider closing the pop-up preview window automatically when the user performs this action. Currently, despite clicking the app's dock icon to summon the app, the user still has to either a) select an item in the pop-up preview to dismiss it, or b) click elsewhere to dismiss it. This feels awkward and inelegant.

**Comment by ejbills** [comment]
I will implement this functionality. However, you do not need to click on anything in the hover window to close it. Simply moving your mouse away from the hover window will hide it automatically.
