### ISSUE TITLE
Feature Request: Replace size dropdown with a slider and number text box, with a preview

### ISSUE THREAD

**Issue by YousufSSyed** [ejbills/DockDoor#83]
- Window size slider
- Number text box
- Window size preview in settings

This would allow for fine-grain control for users to get the exact size they want.

**Comment by illavoluntas** [comment]
Yes, the actual system may be fun but quite unpractical. Adding a preview (for example of the config window) under the slider might also be useful to see the difference.

**Comment by ejbills** [comment]
Was added in previous updates, forgot to close this issue.
