### ISSUE TITLE
Feature Request: limit the width to X number of windows, make new rows for extra windows

### ISSUE THREAD

**Issue by YousufSSyed** [ejbills/DockDoor#84]

**Comment by MattSuda** [comment]
Yes this would be great! I miss this from HyperDock

**Comment by ejbills** [comment]
Need to do this

**Comment by ejbills** [comment]
Almost done with this, working on it!

**Comment by ejbills** [comment]
https://github.com/user-attachments/assets/8332a226-5fb8-4044-a474-db003d9907d0

Work in progress preview
