### ISSUE TITLE
Enhancement: Translation into French

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#89]
I wanted to know I could help translating the app in French, as I am a native French speaker. If yes, how?

**Comment by ejbills** [comment]
Do you have Xcode?

**Comment by illavoluntas** [comment]
@ejbills Yes, I have Xcode.

**Comment by ejbills** [comment]
Ok, please check out the new branch named 'localization' on this repo. Inside xcode, you will see a file like so:
<img width="229" alt="Screenshot 2024-07-08 at 12 37 45 PM" src="https://github.com/ejbills/DockDoor/assets/74191134/ca0a7acc-ee5c-48bb-b349-790a4fb56fc1">

Then, inside the file are all the labels:
<img width="1271" alt="Screenshot 2024-07-08 at 12 38 07 PM" src="https://github.com/ejbills/DockDoor/assets/74191134/3526aee8-e3ea-439d-8daf-b66976f6288a">

So, just add french here:
<img width="800" alt="Screenshot 2024-07-08 at 12 38 50 PM" src="https://github.com/ejbills/DockDoor/assets/74191134/dbd38d83-7517-483e-913e-7e8032293f9e">

And then you will be able to see all of the French labels inside that localization file. Very simple, let me know if you need any help adding french :) Thanks a ton!

**Comment by illavoluntas** [comment]
You are welcome @ejbills! I will look deeper on this tomorrow as it is getting late where I live.

**Comment by illavoluntas** [comment]
@ejbills I forked the project; what will I or you have to do when I will be done translating?

**Comment by ejbills** [comment]
Just commit and push your translations to your fork and then I can take it from there

**Comment by ShlomoCode** [comment]
> Ok, please check out the new branch named 'localization' on this repo

@illavoluntas Now you can check #main instead

**Comment by illavoluntas** [comment]
> > Ok, please check out the new branch named 'localization' on this repo
> 
> @illavoluntas Now, check #main instead

What do I have to do on #main?

**Comment by illavoluntas** [comment]
@ejbills Did you put all the labels in the Localizable file?
I don't see options as this.

![Capture d’écran 2024-07-09 à 08 36 57](https://github.com/ejbills/DockDoor/assets/174935274/5c39661a-5021-4745-9635-da4b78aa7b93)

**Comment by illavoluntas** [comment]
Done for now. See #109 instead.

I am available to update French translations for future versions of DockDoor (from **1.0.17** on) until **July 11th, 2024**, then I will be back on **July 23rd, 2024**. Between July 11th and July 23rd I will have no access to Xcode, but you can try to contact me via this issue by mentioning me, then manually input my translations.

Afterwards, I will make all the modifications that are necessary to keep the translations up to date when a new version is published (maybe a preview of the updated Localizable file should be committed before a new version).

**Comment by illavoluntas** [comment]
Done for now. See #109 instead.

I am available to update French translations for future versions of DockDoor (from **1.0.17** on) until **July 11th, 2024**, then I will be back on **July 23rd, 2024**. Between July 11th and July 23rd I will have no access to Xcode, but you can try to contact me via this issue by mentioning me, then manually input my translations.

Afterwards, I will make all the modifications that are necessary to keep the translations up to date when a new version is published (maybe a preview of the updated Localizable file should be committed before a new version).

**Comment by ShlomoCode** [comment]
https://github.com/xiles/XCStringsEditor

**Comment by ShlomoCode** [comment]
https://www.reddit.com/r/iOSProgramming/comments/17vts5d/new_free_tool_to_localize_your_app_in_seconds/

**Comment by illavoluntas** [comment]
@ShlomoCode I found an [app](https://apps.apple.com/us/app/localizator-xcloc-xcstrings/id6449774982) on iOS that could do the job. I hope it isn't going to become paid on the next day... Anyway, I guess I will also be available!

**Comment by ShlomoCode** [comment]
Actually we need to interface to a friendly translation interface for beginners who don't know how to deal with Git, XCode, etc. See https://github.com/ejbills/DockDoor/issues/114

**Comment by illavoluntas** [comment]
> Actually we need to interface to a friendly translation interface for beginners who don't know how to deal with Git, XCode, etc. See #114

I'm not sure I get what are these.

**Comment by ShlomoCode** [comment]
The idea is to have some kind of URL where you only need to open an account and start contributing translations. Without downloading files, installing XCode which weighs 13GB, etc.
A lot of open source projects do that.

**Comment by illavoluntas** [comment]
That’s interesting!

**Comment by ejbills** [comment]
@illavoluntas please use the new crowdfin integration listed in the readme "Help translate the app"

It will automatically manage syncing the translations, no more Xcode or git issues!

**Comment by illavoluntas** [comment]
Understood @ejbills!
