### ISSUE TITLE
Bug: Impossible to use Tab with default MacOS keybind activated

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#92]
When macOS default keybind (Cmd + Tab) is activated in 1.0.16, it is impossible to use the regular Tab key (tested in VS Code and [Vivaldi](https://vivaldi.com) browser).

At the beginning of the video I struggled unintentionally with the custom keybind. It is more interesting from 00:26.
With the custom keybind enabled I pressed Tab on a Google page and in VS Code.
With Cmd + Tab enabled I also pressed Tab on Google and on VS Code, without success.

https://github.com/ejbills/DockDoor/assets/174935274/3b82dda7-1e94-4d21-848d-c3f45785e0b4

**Comment by illavoluntas** [comment]
Is anyone able to reproduce this problem?

**Comment by hasansultan92** [comment]
Hi @illavoluntas, very good catch! I was able to replicate this, looking to apply a patch to correct my work

**Comment by illavoluntas** [comment]
Glad I could help @hasansultan92!
